### PR TITLE
marker cleanup continued

### PR DESCRIPTION
**Pull request by felix-salfelder**
these overdue changes have appeared while working on issue #285. nothing really changes yet...

### CODE REVIEW

**Comment by in3otd** [comment]
I did some quick testing and LGTM. (but sometimes wondered what the `// BUG` comments were about exactly, it was not always obvious to me...)

**Comment by felix-salfelder** [comment]
thank you.

most `// BUG` comments indicate misplaced code, code that does not do the right thing, or code that shouldn't be there at all, scheduled for cleanup. i started to add them to lines that i had to modify, but couldn't do things right yet...

i will try to be more verbose in future comits.

**Comment by felix-salfelder** [comment]
four more commits, nothing changes. hopefully nothing breaks either...

**Comment by guitorri** [comment]
It is crashing when I try to open this schematic (.dat file added for convenience):
https://gist.github.com/guitorri/667304e29ea41eb3391c

This is from the crash report:
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff99317866 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff8faf535c pthread_kill + 92
2   libsystem_c.dylib             	0x00007fff8cf3db1a abort + 125
3   libsystem_c.dylib             	0x00007fff8cf079bf __assert_rtn + 321
4   org.qucs                      	0x000000010f81b01c Graph::ScrPt::setScrY(float) + 92 (graph.cpp:325)
5   org.qucs                      	0x000000010f81b076 Graph::ScrPt::setScr(float, float) + 54 (graph.cpp:332)
6   org.qucs                      	0x000000010f8246f2 Diagram::calcCoordinateP(double const*, double const*, double const*, std::__1::__wrap_iter<Graph::ScrPt*>&, Axis const*) const + 146 (diagram.cpp:2047)
7   org.qucs                      	0x000000010f822531 Diagram::calcData(Graph*) + 1761 (diagram.cpp:522)
8   org.qucs                      	0x000000010f826f7b Diagram::updateGraphData() + 299 (diagram.cpp:848)
9   org.qucs                      	0x000000010f8255a4 Diagram::loadGraphData(QString const&) + 964 (diagram.cpp:805)
10  org.qucs                      	0x000000010f45e822 Schematic::reloadGraphs() + 210 (schematic.cpp:1261)
11  org.qucs                      	0x000000010f45d92f Schematic::becomeCurrent(bool) + 1695 (schematic.cpp:224)
12  org.qucs                      	0x000000010f45e90c non-virtual thunk to Schematic::becomeCurrent(bool) + 44 (schematic.cpp:226)
13  org.qucs                      	0x000000010f480ba8 QucsApp::slotChangeView(QWidget*) + 456 (qucs.cpp:1745)
14  org.qucs                      	0x000000010f474a1e QucsApp::gotoPage(QString const&) + 1902 (qucs.cpp:1385)
15  org.qucs                      	0x000000010f47a6ca QucsApp::slotOpenContent(QModelIndex const&) + 970 (qucs.cpp:2204)
```

**Comment by felix-salfelder** [comment]
@guitorri just loading and plotting from your dat does not seem to crash. am I supposed to open this in connection with a schematic?

(i suspect this has something to do with S parameter stuff...)

thank you

**Comment by felix-salfelder** [comment]
@guitorri interesting corner case. i suspect that negative y are intended here (i did not introduce them, afaics). with dbd3376 all plots from `sparam.sch` look like master to me.

maybe collecting test plots is not too bad a thing to do... `:)`

**Comment by in3otd** [comment]
@guitorri do you think the `-print` option of `qucs` could be expanded to print also the Data Display files? This could maybe allow to have an equivalent `qucs-test` for the diagrams...

**Comment by guitorri** [comment]
That was the idea of having `-print` from the command line. :smile:  To automate generation of reports, documentation and testing... Indeed, my intention is to eventually hook it up into `qucs-test`. I don't remember why I did not try to print the .dpl files. I recall moving some diagrams into the schematic because of this limitation. If you come up with something let me know.

**Comment by guitorri** [comment]
This looks good to me. Let me check #297, then I can merge only that PR right?

**Comment by in3otd** [comment]
it seems that, in general, `qucs` can already print also the `.dpl` files. I didn't try that before...
Following your suggestion, I expanded a bit `qucs-test` to allow printing of `.sch` only, `.dpl` only or both and to have a (sort of) comparison between two different `qucs` version, similar to what can already be done for `qucsator`. See https://github.com/Qucs/qucs-test/pull/7 .

**Pull request closed without merging**
