### PR TITLE
Fix Some GUI Issues (WIP)

### PR DESCRIPTION
**Pull request by nvdl**
Right click rotate when inserting a new component does not create ghosting.
Component movement after placement does not create ghosting.
Component is realigned to grid if previously misaligned using Ctrl key.
Selection box is broken in this commit and needs fixing.

### CODE REVIEW

**Comment by nvdl** [comment]
Work In P.

**Comment by in3otd** [comment]
[rant mode on]
- please avoid mixing whitespace changes with functional changes: this increases the burden of the reviewers, which have to sort out significant and non-significant changes. It's ok if you use a different coding style for a new block of code you add or modify entirely, though it will be better if it uses the style of the surrounding code.
If you really cannot stand the existing (mixed) coding style:
  - try harder to accept it
  - if the above fails, please separate out the whitespace-only changes in an independent commit, so that it will be reviewed only once (while the functional changes *will* be read more than once)
`git rebase -i` and `git add -p` are your friends.

- why did you leave in leaving in old line of codes after commenting them out? We use a revision control system also to avoid things like these. A `diff` already tells what has been changed, no need to leave the old code in.

[rant mode off]

 apart from that, it seems fine so far, after a very quick test

If it's a work in progress, please add it in the title ("`[WIP]`") also (and remove it once you think it's finished).

**Comment by nvdl** [comment]
> please separate out the whitespace-only changes in an independent commit, so that it will be reviewed only once (while the functional changes will be read more than once

Makes sense.

> try harder to accept it

Still trying to get used to organic growth.
We had a plan for code formatting. What happened to that?

**Comment by in3otd** [comment]
> We had a plan for code formatting. What happened to that?

We still have a plan, I think. It's just postponed to after more important things have been taken care of. And I seem to remember we didn't reach an agreement on how/when do that. (reopen the discussion in the old thread, if you *really* like to :grin:)

> Keeping that for a while if something breaks (easier to spot). Will be removed in the end.

Thanks.

**Comment by nvdl** [comment]
> We still have a plan, I think. It's just postponed to after more important things have been taken care of.

Yes, we may take that later. But I like the idea of one commit only dedicated to formatting. Those misplaced braces, spaces, comments etc. really distract me.

**Comment by guitorri** [comment]
What is the situation here? I want to close the release.

**Comment by nvdl** [comment]
Still in progress. Do not pull.

**Comment by guitorri** [comment]
Moved base to `develop`.

**Pull request closed without merging**
