### PR TITLE
Add CMake and flatpak build support

### PR DESCRIPTION
**Pull request by Murmele**
- Until now only autotools was supported. Get CMake support which was already once for an older Qucs version available work again with Qt5.
- Add flatpak support for qucs, qucsator is not shown yet, has to be checked out why
- Initialize all pointers with a nullptr, so they have a defined state

### CODE REVIEW

**Comment by felix-salfelder** [comment]
On Mon, Dec 28, 2020 at 08:57:53AM -0800, Murmele wrote:
> - Until now only autotools was supported. Get CMake support which was
> already once for an older Qucs version available work again with Qt5.
> - Add flatpak support for qucs, qucsator is not shown yet, has to be checked out why
> - Initialize all pointers with a nullptr, so they have a defined state

too many things at once. I will try and get the cmake stuff over the
line.

- why not #include(GNUInstallDirs)?
- the cmake files are missing a header with author(s) and license.
   (i know it's not your fault, but this is a good time to fix it, as
	you probably want to add your name)
- compileAndInstallDependencies.cmake does not work like this. qucs only
   depends on Qt right now. qucs-pkg (aka the top level) could be used to
   install more stuff.
- not sure I understand the library structure, I will have to run it...

(will get back to the other changes).

**Comment by Murmele** [comment]
> - why not #include(GNUInstallDirs)?

I don't know what it is. It works without. Therefore I removed.

> - compileAndInstallDependencies.cmake does not work like this. qucs only depends on Qt right now. qucs-pkg (aka the top level) could be used to install more stuff.

Yes but for debugging Qucs, you need some libraries (legacy, painting, ...) this script should copy into a common place. The idea is to just make it ready to go. Build and debug and no other things must be compiled



> - not sure I understand the library structure, I will have to run it...

what do you mean?

**Comment by felix-salfelder** [comment]
On Mon, Dec 28, 2020 at 09:30:18AM -0800, Murmele wrote:
> > - not sure I understand the library structure, I will have to run it...
> 
> what do you mean?

coreSchematic and qucsschematic

in autotools I only have "libqucs" (at the moment), while the contents
may change, the role of that library will not.

**Comment by felix-salfelder** [comment]
I did a partial merge, with added TODOs.

where are the rules for the plugins, or do you intend to compile them at
startup?

**Comment by Murmele** [comment]
> On Mon, Dec 28, 2020 at 09:30:18AM -0800, Murmele wrote: > - not sure I understand the library structure, I will have to run it... what do you mean?
> coreSchematic and qucsschematic in autotools I only have "libqucs" (at the moment), while the contents may change, the role of that library will not.

This was already there. But yes it makes not that much sense. I can change it after the merge

**Comment by Murmele** [comment]
> plugins, or do you intend to compile them at

You mean attenuator ...? They are not yet included. There is a add_subdirectory() where they are included. As soon as they are working perfectly we can add them

**Comment by felix-salfelder** [comment]
On Mon, Dec 28, 2020 at 10:11:33AM -0800, Murmele wrote:
> > plugins, or do you intend to compile them at
> 
> You mean attenuator ...? They are not yet included. There is a
> add_subdirectory() where they are included. As soon as they are
> working perfectly we can add them

i mean plugins/* and legacy/* and contrib/*

attenuator is not a plugin, but a tool.

**Comment by felix-salfelder** [comment]
I am back to

../src/libqucsschematic.so: undefined reference to `DiagramDialog::DiagramDialog(QucsDoc*)'

libqucsschematic should be libqucs. with autotools I get

$ nm path/to/libqucs.so | c++filt |grep ::Diag
00000000001aef78 W DiagramList::DiagramList()
00000000001aef78 W DiagramList::DiagramList()
000000000023df26 T DiagramDialog::DiagramDialog(QucsDoc*)
000000000023df26 T DiagramDialog::DiagramDialog(QucsDoc*)
000000000011b9fc T Diagram::Diagram(int, int)
000000000011b606 T Diagram::Diagram(Diagram const&)
000000000011b9fc T Diagram::Diagram(int, int)
000000000011b606 T Diagram::Diagram(Diagram const&)

hth

**Comment by Murmele** [comment]
> i mean plugins/* and legacy/* and contrib/*

they are build with the application. compileAndInstallDependencies.cmake installs these dependencies if preferred (if CompileDependencies option is ON). Otherwise the dependencies will not be build

**Comment by felix-salfelder** [comment]
On Mon, Dec 28, 2020 at 10:26:49AM -0800, Murmele wrote:
> > i mean plugins/* and legacy/* and contrib/*
> 
> they are build with the application. compileAndInstallDependencies.cmake installs these dependencies if preferred (if CompileDependencies option is ON). Otherwise the dependencies will not be build

they are not dependencies. the plugins must be built from the top level
cmakefile. on some systems they must be built after the library.

maybe you can use one CmakeFile for all plugins. given that it reads
MakeLists as intended.

**Comment by Murmele** [comment]
> I am back to ../src/libqucsschematic.so: undefined reference to `DiagramDialog::DiagramDialog(QucsDoc*)' libqucsschematic should be libqucs. with autotools I get $ nm path/to/libqucs.so | c++filt |grep ::Diag 00000000001aef78 W DiagramList::DiagramList() 00000000001aef78 W DiagramList::DiagramList() 000000000023df26 T DiagramDialog::DiagramDialog(QucsDoc*) 000000000023df26 T DiagramDialog::DiagramDialog(QucsDoc*) 000000000011b9fc T Diagram::Diagram(int, int) 000000000011b606 T Diagram::Diagram(Diagram const&) 000000000011b9fc T Diagram::Diagram(int, int) 000000000011b606 T Diagram::Diagram(Diagram const&) hth

maybe it is because you did not merge everything?

**Comment by felix-salfelder** [comment]
On Mon, Dec 28, 2020 at 11:10:30AM -0800, Murmele wrote:
> > I am back to ../src/libqucsschematic.so: undefined reference to `DiagramDialog::DiagramDialog(QucsDoc*)' libqucsschematic should be libqucs. with autotools I get $ nm path/to/libqucs.so | c++filt |grep ::Diag 00000000001aef78 W DiagramList::DiagramList() 00000000001aef78 W DiagramList::DiagramList() 000000000023df26 T DiagramDialog::DiagramDialog(QucsDoc*) 000000000023df26 T DiagramDialog::DiagramDialog(QucsDoc*) 000000000011b9fc T Diagram::Diagram(int, int) 000000000011b606 T Diagram::Diagram(Diagram const&) 000000000011b9fc T Diagram::Diagram(int, int) 000000000011b606 T Diagram::Diagram(Diagram const&) hth
> 
> maybe it is because you did not merge everything?

don't know, I think I built the library with src/CmakeList.txt

$ nm src/libqucsschematic.so | c++filt |grep :Diag
000000000019b7fa W DiagramList::DiagramList()
000000000019b7fa W DiagramList::DiagramList()
                 U DiagramDialog::DiagramDialog(QucsDoc*)
000000000011a906 T Diagram::Diagram(int, int)
000000000011a584 T Diagram::Diagram(Diagram const&)
000000000011a906 T Diagram::Diagram(int, int)
000000000011a584 T Diagram::Diagram(Diagram const&)

the "U" is wrong. what do you get?

**Comment by Murmele** [comment]
I get:
nm libqucsschematic.so | c++filt |grep :Diag 
00000000001ace9c W DiagramList::DiagramList()
00000000001ace9c W DiagramList::DiagramList()
00000000001ecc9c T DiagramDialog::DiagramDialog(QucsDoc*)
00000000001ecc9c T DiagramDialog::DiagramDialog(QucsDoc*)
00000000001269a6 T Diagram::Diagram(int, int)
0000000000126602 T Diagram::Diagram(Diagram const&)
00000000001269a6 T Diagram::Diagram(int, int)
0000000000126602 T Diagram::Diagram(Diagram const&)

Here I build the complete qucs project

**Comment by felix-salfelder** [comment]
On Mon, Dec 28, 2020 at 11:25:24AM -0800, Murmele wrote:
> I get:
> nm libqucsschematic.so | c++filt |grep :Diag 
> 00000000001ace9c W DiagramList::DiagramList()
> 00000000001ace9c W DiagramList::DiagramList()
> 00000000001ecc9c T DiagramDialog::DiagramDialog(QucsDoc*)
> 00000000001ecc9c T DiagramDialog::DiagramDialog(QucsDoc*)
> 00000000001269a6 T Diagram::Diagram(int, int)
> 0000000000126602 T Diagram::Diagram(Diagram const&)
> 00000000001269a6 T Diagram::Diagram(int, int)
> 0000000000126602 T Diagram::Diagram(Diagram const&)
> 
> Here I build the complete qucs project

hmm, you got the symbol twice (odd).

but it was in fact a MakeList issue, they were in DIALOG_SRC2 maybe from
another cleanup attempt.

**Comment by felix-salfelder** [comment]
On Mon, Dec 28, 2020 at 08:51:12PM +0100, Felix Salfelder wrote:
> but it was in fact a MakeList issue, they were in DIALOG_SRC2 maybe from
> another cleanup attempt.

(it works)

can you add a flag to enable debug mode? i need
-O0 -g -UNDEBUG -DTRACE_UNTESTED -Wall

it should be documented in the README file (or some other standard
place). I could not find it.

thanks.

**Comment by Murmele** [comment]
yes of course. Did you merge all? I will add an option for it

**Pull request closed without merging**
