### PR TITLE
rearrange libraries

### PR DESCRIPTION
**Pull request by felix-salfelder**
- backport from component cleanup (untested)
- one more library
- switch to shared private libraries
- use libtool

### CODE REVIEW

**Comment by felix-salfelder** [comment]
rebases. some parts are already in, such as libtool

**Comment by felix-salfelder** [comment]
now i'm seeing these en/decode string missing symbols, but on appveyor. @guitorri do you remember how to get around these? is there an extra library i need to link to?

**Comment by guitorri** [comment]
Try this:
https://github.com/Qucs/qucs/blob/develop/qucs-core/src/Makefile.am#L45-L46

**Comment by felix-salfelder** [comment]
thanks. right direction.

i guess it's better to only clutter the global namespace with what we need. trying to figure that out.

what is the preferred way to check if this is built on win? i could only find `#ifdef _WIN32`, but that looks like 32 bit, no? background: platform.hpp uses `#ifdef MS_DLL`, but that's not in config.h.

**Comment by in3otd** [comment]
FYI, https://msdn.microsoft.com/en-us/library/b0084kay.aspx :
*<b>_WIN32</b> Defined as 1 when the compilation target is 32-bit ARM, 64-bit ARM, x86, or x64. Otherwise, undefined.*

**Comment by felix-salfelder** [comment]
@in3otd thanks. currently it checks whether `__MINGW32__` is defined, will consider to add `_WIN32`. good to know that `32` does not have any (relevant) meaning.

anyway, are there any differences to expect between mingw (what appveyor does) vs. m$visual compiler (the one you linked to)?

**Comment by in3otd** [comment]
I think that `_WIN32` is always defined in Windows for the compilers we typically use.
[Here](http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system#WindowswithCygwinPOSIX) is a page with some details on which macros are defined when, not sure if it's up to date.

**Comment by felix-salfelder** [comment]
doesn't do much. but it's ready. will do more in another PR.

**Pull request merged**
