### PR TITLE
Merge release fixes into develop

### PR DESCRIPTION
**Pull request by guitorri**
Apply `release-` fixes to `develop`.

### CODE REVIEW

**Comment by in3otd** [comment]
Travis PR build is failing because unfortunately currently `develop` is broken, need #871 to fix that.
I'll rebase #871 on the current develop to have Travis passing there, then you can rebase/remerge this again...

**Comment by in3otd** [comment]
um, this PR merge on develop fails because it needs #871, #871 build fails because it needs #870 also on `develop`, so I think the only solution is to cherry-pick #870 on `develop` and then merge #871 there. before re-doing this PR..

**Comment by in3otd** [comment]
um, this PR merge on develop fails because it needs #871, #871 build fails because it needs #870 also on `develop`, so I think the only solution is to cherry-pick #870 on `develop` and then merge #871 there. before re-doing this PR..

**Comment by felix-salfelder** [comment]
has been merged through 0.0.20-1. please reopen if i am getting this wrong.

**Pull request closed without merging**
