### PR TITLE
MutualX fix

### PR DESCRIPTION
**Pull request by ra3xdh**
There is a fix for #213

### CODE REVIEW

**Comment by ra3xdh** [comment]
Don't merge it. This PR is not ready.

**Comment by ra3xdh** [comment]
Now it is ready for merge

**Comment by in3otd** [comment]
LGTM, but I think there is no need to keep the intermediate corrections to the fixes in the global history, you can probably squash everything into just one or two commits...

**Comment by ra3xdh** [comment]
@in3otd There are two points of view on commits amount: to unite all in a big commit and to store every change in a separate commit. I prefer a second way. It allows to store full history of changes and extract diffs from commit history when it is needed. So, my opinion is to leave commits in this PR as is.

**Comment by in3otd** [comment]
well, I understand it's a matter of opinion and I am not saying we should pull just a single commit for all the changes every time, but, for example, in this particular case I do not see the value in keeping both 7f56fe71a155a0c79e977ef56cea749e6f73d66d and 9885b017d25851bebcfbe3720c7bff91129e9f9e separate in the `Qucs` history. Same for d748874b8eb804c3d093e3fd5404e1d38c66559f and bd2353cea89803ca01bedfb4e78be573e3834ec2 . The first commit 344bcc2c3812b5bfc892ed5b940c9835dc2a4ff8 is also largely rewritten by the following commits. There are 6 commits modifying practically always the same lines in 2 files. 

If we will ever need to check this code some time in the future (hopefully not...) the details of *how* we got to the final solution won't really be useful, again IMHO.

Other points of view are welcome... :smile:

**Comment by ra3xdh** [comment]
@in3otd Reduced number of commits, please check

**Comment by in3otd** [comment]
merged, but for some reason Github did not close the PR automatically (maybe because I closed from from the command line...)

**Pull request closed without merging**
