### PR TITLE
Fix Travis exit code in if statements

### LINKED ISSUE #776: Travis sometimes appear to pass even if failing
see e.g. [here](https://github.com/Qucs/qucs/pull/774#issuecomment-364634101)

### PR DESCRIPTION
**Pull request by in3otd**
testing

Fixes #776 hopefully

### CODE REVIEW

**Comment by in3otd** [comment]
oh, "nice", it works as expected... Travis now fails **due to errors also present in previous commits** :open_mouth: 
See e.g. the previously "passing" builds logs at
https://travis-ci.org/Qucs/qucs/jobs/352609034#L5497
and
https://travis-ci.org/Qucs/qucs/jobs/352609031#L3840

**Comment by felix-salfelder** [comment]
what a great find ... i can't help but summarise.

cmake says

    ../libqucsator.so: undefined reference to `dlopen'
    ../libqucsator.so: undefined reference to `dlclose'
    ../libqucsator.so: undefined reference to `dlerror'
    collect2: error: ld returned 1 exit status

and on apple there is a problem with python

    ImportError: No module named mpl_toolkits.mplot3d.axes3d

**Comment by in3otd** [comment]
>and on apple there is a problem with python
>`ImportError: No module named mpl_toolkits.mplot3d.axes3d`

yep, probably related to this Travis message about the build:
*This job was configured to run on an OS X image that was retired on November 28, 2017. It was routed to our Xcode 8.3 image.*
I guess we need @guitorri here or I could try some random fix, hoping not to break other things

**Comment by guitorri** [comment]
The Linux/Cmake dlopen error is fixed in 51af50ca480b33ffd79e5147d16cdd67b77e7004. Need to merge #757.
 
I will take a look at the OSX instance.

**Comment by guitorri** [comment]
I think I found the matplotlib issue. Homebrew changed things and pip is now either `pip2` or `pip3`.
```/Users/travis/.travis/job_stages: line 57: pip: command not found```

**Comment by felix-salfelder** [comment]
what's the point in plotting figures in a test suite?

this looks like an opportunity to get rid of it (or make it optional). will that affect any of the actual testing?

**Pull request merged**
