### PR TITLE
toplevel makefile & co.

### PR DESCRIPTION
**Pull request by felix-salfelder**
needed to build/test the project as a whole. also unifies the bootstrap
scripts amongst the subprojects.

what shall we do about the TODO, NEWS, AUTHORS, ChangeLog? i think it's best to just reference the corresponding `*/$file`s...

### CODE REVIEW

**Comment by guitorri** [comment]
Can't we set it to AM_INIT_AUTOMAKE to foreign and ignore the TODO, NEWS for now?

Perhaps enable/disable flag for each of the three sub directory?

**Comment by felix-salfelder** [comment]
> foreign
 
daccord

> Perhaps enable/disable flag for each of the three sub directory?

the toplevel AM_ options are independent of the others.

**Comment by guitorri** [comment]
I mean, something like --disable-qucs-doc, to skip the build?

**Comment by felix-salfelder** [comment]
ok, added a `--disable-doc` option, makes a lot of sense sense for distcheck.

**Comment by felix-salfelder** [comment]
i consider distcheckability important, added to 0.0.19

travis is unhappy about the bootstrap cleanup, (how) can i fix this?

**Comment by in3otd** [comment]
> travis is unhappy about the bootstrap cleanup, (how) can i fix this?

I think you should modify the top-level `.travis.yml` to use your new bootstrap scheme...

**Comment by in3otd** [comment]
it seems that the building process for Travis is still not right https://travis-ci.org/Qucs/qucs/jobs/81184336#L1104-L1118 ??

**Comment by felix-salfelder** [comment]
thanks for the reminder. however without #361 this PR won't help a lot.

(will squash all commits as soon as tests pass)

**Comment by guitorri** [comment]
I was ready to merge this, but two things popped up: 
- Can you take a look at the conflicts created with the merge of #294?
- Perhaps you can update at references to autogen.sh in the readme files.
Thanks!

**Comment by felix-salfelder** [comment]
i rebased toplevel to master. i did not see any conflicts (maybe newer git here?).
also replaced all occurrences of autogen.sh i could find.

thanks
felix

**Pull request merged**
