### PR TITLE
qucs#956 command line

### PR DESCRIPTION
**Pull request by oxmon-2500**
- qucs without arguments working as previously
- qucs with arguments see usage
The following statements in qucs.cpp do not work as supposed (no any action):
  //-------------------------------------------------------------------------------------------------------
  // select (highlight) project in QListView (projects)
  QModelIndex idx = m_homeDirModel->index(openProjName, 0); //FIXME
  Projects->selectionModel()->select(idx, QItemSelectionModel::Select); //FIXME
  //-------------------------------------------------------------------------------------------------------
Possible someone with Qt-experience can solve it in the future

### CODE REVIEW

**Comment by in3otd** [comment]
there are too many, apparently unrelated, changes and it's difficult to readily understand what are the actual functional changes.

Whitespace/indentation changes in code that did not need to be touched otherwise should not be done, see the [coding conventions](https://github.com/Qucs/qucs/wiki/Contribution#coding-conventions) in the [Contributing](https://github.com/Qucs/qucs/wiki/Contribution) guidelines.
If you really, really, really need to change the existing whitespace (hint: you usually don't), those changes should go in a separate commit.

**Comment by oxmon-2500** [comment]
> there are too many, apparently unrelated, changes and it's difficult to readily understand what are the actual functional changes.
> 
> Whitespace/indentation changes in code that did not need to be touched otherwise should not be done, see the [coding conventions](https://github.com/Qucs/qucs/wiki/Contribution#coding-conventions) in the [Contributing](https://github.com/Qucs/qucs/wiki/Contribution) guidelines.
> If you really, really, really need to change the existing whitespace (hint: you usually don't), those changes should go in a separate commit.

The problem lies in not updated tests module SchematicTests.cpp and I hope the next travis run will be OK. 
Regarding white space I deactivate spaces-compare in diff-programs, but you are right to make as few as possible unrelated changes.

**Comment by in3otd** [comment]
I'll let you fix the Travis error; I have already split your initial commit in a few parts, separating the whitespace changes (which will be removed). Once CI is passing I'll push these changes on top of your commits, so you can take a look. Later I'll squash the unneeded commits.
I did a quick test and the added option seems to work as expected also here.

**Comment by in3otd** [comment]
Note that OSX has a new error, independent of the code from this PR:
see line 99 [here](https://travis-ci.org/Qucs/qucs/jobs/653894775#L99) or below.
As a consequence Qt4 is not installed and the configuration fails.
@guitorri ?

```
$ rvm $brew_ruby do brew bundle --verbose --global
/usr/local/bin/brew tap homebrew/bundle
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
Tapped (102 files, 250.9KB).
Error: Unknown command: bundle
```

**Comment by guitorri** [comment]
https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296/15

**Comment by in3otd** [comment]
ah, thanks - my google-fu was weak apparently :grin:.
I've opened #975 to fix that.

**Comment by in3otd** [comment]
I've split your changes, grouping them broadly according to their purpose. There are a few reverts just to avoid force-pushing, for the moment. Later this will be rebased on the latest develop and those reverts squashed/removed.

I see that after all the changes, I now appear to be the author of all the commits, I'll fix that when rebasing.

**Comment by guitorri** [comment]
Please rebase and cleanup history. 
One commit for your feature, another for the whitespace (if you must).

**Comment by oxmon-2500** [comment]
> Please rebase and cleanup history.
> One commit for your feature, another for the whitespace (if you must).

Hi, after checks are OK I am going to rebase:
git rebase -i 5c696ce  (the first commit in the feature branch) Makes it also cleanup history, or is there an another git command?

**Comment by guitorri** [comment]
It is good practice to update develop and rebase on top of it.

Something like:

```
git checkout develop
git pull [origin] develop #origin is the project remote
git checkout [feature]
git rebase develop # put your [feature] branch on top of develop.
```

**Comment by in3otd** [comment]
I'd suggest to use `-i` with `rebase` so that you can choose whether to squash/skip some commits

**Comment by oxmon-2500** [comment]
> I'd suggest to use `-i` with `rebase` so that you can choose whether to squash/skip some commits

Its already done: git rebase -i e93a709
all lines changed to squash, except:
pick 5c696ce qucs#956 command line (first line)
pick d5f9d79 Fix Graph loading when Dataset names contain spaces
pick cb15cd0 Add a tutorial on lineal blocks and frequency response
I hope this is OK, if not I will delete this PR and make a new one with only one commit.

By the way, I am creating a git-wiki-page with the workflow step-by-step:
https://github.com/oxmon-2500/qucs_wiki/wiki
Any suggestion to change/expand it would be appreciated
Cheers

**Comment by oxmon-2500** [comment]
A new PR#981 **Qucs 956 command line clean** replaces this one

**Comment by in3otd** [comment]
in general there is no need to open a new PR if you are working on the same changes; just `push --force` your changes to the same branch.

**Comment by guitorri** [comment]
@oxmon-2500, I see you are struggling with rebase.
Before doing a PR, get used to update `develop` from upstream and rebase your branch with respect to the latest `develop`.
Ideally the PR should contain only your fixes, not commits that are already merged into `develop`.
Right now you are using a very old commit to rebase. This way the rebase will pick up commits in between that have nothing to to do with your PR.
Whenever possible work based on the latest `develop`.

I typically use the following:
```
git checkout develop
git pull [origin] develop   #origin is the project remote
git checkout [feature]
git rebase develop  # put your [feature] branch on top of develop
git checkout -b feature-cleanup  # new branch for cleanup operation
git rebase -i develop  # iterative rebase cleanup the mess, keep original branch just in case
git push -f guitorri feature-cleanup:feature # overwrite branch on existing PR
```

**Pull request closed without merging**
