### PR TITLE
try to make check in appveyor

### PR DESCRIPTION
**Pull request by felix-salfelder**
want to see what happens...

### CODE REVIEW

**Comment by in3otd** [comment]
don't know what happened, but AppVeyor seemed to pass but didn't actually include the last commit (see [here] (https://ci.appveyor.com/project/qucs/qucs/build/1.0.674)
I have restarted it and now the added `make check` is there, but it fails...

**Comment by felix-salfelder** [comment]
strange. thanks for noticing at all...

**Comment by felix-salfelder** [comment]
anyway, this is failing. should we consider this an issue for 0.0.19?

(if so: can somebody please fix it? through appveyor, this is no fun and takes ages.)

**Comment by in3otd** [comment]
fail message is
```
make[3]: *** No rule to make target 'libqucsUnitTest.exe', needed by 'libqucsUnitTest.log'.  Stop.
make[3]: Leaving directory '/c/projects/qucs/qucs-core/tests'
Makefile:939: recipe for target 'check-TESTS' failed
```
which I think comes from [here] (https://github.com/Qucs/qucs/blob/master/qucs-core/tests/Makefile.am#L51-L55). But even if that was working, I think it's doing actually nothing if [gtest] (https://github.com/google/googletest) is not installed, so it will need additional stuff in `.appveyor.yml`
I think we can leave this out for 0.0.19, what do you think @guitorri ?

**Comment by felix-salfelder** [comment]
looks irrelevant now

**Pull request closed without merging**
