### PR TITLE
Lay aside phasor and waveac diagrams

### PR DESCRIPTION
**Pull request by andresmmera**
The aim of this commit is to lay aside the waveac and phasor diagrams since their current implementation makes much more difficult to merge older PR (specifically #370) and entangles the Qucs code. 

In this sense, "phasordiagram.h/.cpp" and "waveac.h/.cpp" were removed from "CMakeLists.txt" and "Makefile.am". The most relevant code spread over "diagram.cpp/h", "marker.cpp/h", etc. was
commented whereas those portions of code that intrude existing functions were removed.
IMHO, an alternative non-intrusive way will be needed to implement these features in the future.

### CODE REVIEW

**Comment by andresmmera** [comment]
Travis says:

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated

I restarted the build but I got the same result. Any guess?

**Comment by in3otd** [comment]
I see both builds get stuck at the same point, after the `qucsator` test, I'm checking locally to see how it behaves.

I fear that once the code is out it will be quite difficult to find the time to refactor it merge it back in; do we have at least some examples to see how these diagrams should work?

**Comment by andresmmera** [comment]
Yes, you can check how the graphs look like in this document (taken from the #682 discussion thread) which contains two examples https://github.com/Qucs/qucs/files/998064/Diagrams.examples.pdf 

> I fear that once the code is out it will be quite difficult to find the time to refactor it merge it back in; do we have at least some examples to see how these diagrams should work?

I fully agree. However, I believe this is the lesser evil. The code related to these features spreads over several files making a lot of conditionals that ends up entangling the (already entangled) diagram code. For example,

https://github.com/qucs/qucs/blob/develop/qucs/qucs/diagrams/diagram.cpp#L62
https://github.com/qucs/qucs/blob/develop/qucs/qucs/diagrams/diagram.cpp#L198
https://github.com/qucs/qucs/blob/develop/qucs/qucs/diagrams/diagram.cpp#L698

https://github.com/qucs/qucs/blob/develop/qucs/qucs/diagrams/diagramdialog.cpp#L294
https://github.com/qucs/qucs/blob/develop/qucs/qucs/diagrams/diagramdialog.cpp#L748
https://github.com/qucs/qucs/blob/develop/qucs/qucs/diagrams/diagramdialog.cpp#L769
https://github.com/qucs/qucs/blob/develop/qucs/qucs/diagrams/diagramdialog.cpp#L821

etc...

IMHO, I shouldn't have merged #682, but now it's done, the least thing I can do is to restore somehow the previous code...

**Comment by in3otd** [comment]
I'm not familiar with the test stuff but I see something strange in the build logs around
```
Running [qucs]:  qucs -n -i testsuite/AC_groupdelay_ac_prj/groupdelay_ac.sch -o testsuite/AC_groupdelay_ac_prj/test_groupdelay_ac.txt
Comparing : diff testsuite/AC_groupdelay_ac_prj/netlist.txt testsuite/AC_groupdelay_ac_prj/test_groupdelay_ac.txt
[92mDiff netlist    : PASS[0m
[94mConverting schematic to netlist.[0m
Running [qucs]:  qucs -n -i testsuite/AC_phasordiag_prj/phasordiag.sch -o testsuite/AC_phasordiag_prj/test_phasordiag.txt

Project :  /home/travis/build/Qucs/qucs/qucs-0.0.19/_build/qucs-test/testsuite/DC_TR_active_mixer_prj
```

there is an `AC_phasordiag_prj` test, which I think should just fail now

**Comment by andresmmera** [comment]
Thanks!! I've just removed the two tests related to PR682

**Comment by in3otd** [comment]
running `distcheck` locally I see why the build/test got stuck: once it gets to the removed diagram test it opens an error box message saying "Format Error: Unknown diagram!" with an `Ok` button, which of course cannot be clicked by the script...
After clicking the `Ok` button, the script fails as expected.

This is of course somewhat related to #756 - X should not be needed for running the tests.

BTW, Travis still fails, but with a slightly different error now

**Comment by andresmmera** [comment]
Surely I'm failing to understand the logic behind the git submodules... but I followed the procedure detailed [here](https://github.com/Qucs/qucs/wiki/Contribution#updating-the-qucs-test-submodule) and it seems that the changes I'm doing locally are not commited/pushed correctly.

Basically, I did the following:
cd qucs-test/
git checkout master
git pull
git rm -r testsuite/AC_temporaldiag_prj/
git rm -r testsuite/AC_phasordiag_prj/
git rm -r testsuite/DC_AC_ohmmeter_prj/
git rm -r testsuite/DC_AC_internal_resistance_prj/
cd ..
git add qucs-test/
git commit --amend

Am I missing something important? :sweat:

**Comment by in3otd** [comment]
I think that the changes to `qucs-test` should be committed to the `qucs-test` repo first, then you can update the `qucs` submodule pointer to `qucs-test`.
The changes you did in `qucs-test` above are just staged in your local repo, the remote repo is unchanged; the commit just "updated" the `qucs` submodule pointer to point to the current commit in `qucs-test`, which was actually not changed (nothing was committed to `qucs-test`)

**Comment by in3otd** [comment]
and maybe, since this should be a temporary thing, you could leave the tests in place and just add them to the exclusions lists [skip.txt](https://github.com/Qucs/qucs-test/blob/master/skip.txt) and [skip_OSX.txt](https://github.com/Qucs/qucs-test/blob/master/skip_OSX.txt)

**Comment by guitorri** [comment]
I fixed it for you. Hope it passes now.

With submodules I do the following: 
1) create branch and commit locally to the qucs-test
2) push qucs-test branch to remote (so other can see your commits)
3) from qucs create branch, git add qucs-test, commit (record new qucs-test hash) and push to remote (to start Travis).

**Comment by andresmmera** [comment]
@guitorri Many thanks!! I found particularly difficult to update the submodules. Thank you for those guidelines!! I'm sure they'll help me in the future :-)

**Comment by guitorri** [comment]
I will merge as is. If the Graph refactor is still hard to merge we might need to clean it up further.

**Pull request merged**
