### PR TITLE
trying to fix LDFLAGS issue #785

### PR DESCRIPTION
**Pull request by felix-salfelder**
see #785

### CODE REVIEW

**Comment by guitorri** [comment]
I think the original defaults were left as a fall-back? Very long ago, the Qt installers for OSX did not ship/install pkg-config files. I don't know if that is still the case.

**Comment by guitorri** [comment]
You also seem to have updated the qucs-test submodule on the first commit.

**Comment by felix-salfelder** [comment]
On Sun, Mar 18, 2018 at 09:47:42PM +0000, Guilherme Brondani Torri wrote:
> You also seem to have updated the qucs-test submodule on the first commit.

eek, that was in error. thanks for the spot!

felix

**Comment by felix-salfelder** [comment]
travis is unhappy.

    no output has been received in the last 10m0s

relation to LDFLAGS and QT_LIBS unclear to me. will have another look, later

**Comment by in3otd** [comment]
I think this is due to the `qucs-test` submodule "update", it seems it's now pointing at a version with a `skip.txt` file which does not including schematic with removed components (like the phasor diagram) so qucs is complaining when opening the schematic and shows a Message Box about that but on Travis nobody can press the *OK* button...
Not sure why the build appears to continue after trying to convert that schematic, the outputs seems a bit out of sync (?)

**Comment by felix-salfelder** [comment]
thanks for the reminder. that makes sense. i thought i had fixed the qucs-test mistake already `:|`

**Pull request closed without merging**
