### PR TITLE
fix Diagram::PaintDiagram visibility

### PR DESCRIPTION
**Pull request by felix-salfelder**
this fixes one of the problems addressed in #370

### CODE REVIEW

**Comment by in3otd** [comment]
um, this is practically a revert of https://github.com/Qucs/qucs/pull/523/commits/c9fcce60b1ddcefcc425a6c909ef6914ccb02a98#diff-12763b2bbd1d04ec7aa8054d6f637f86 and so brings back [this issue](https://github.com/Qucs/qucs/pull/523#issuecomment-226871713)

**Comment by felix-salfelder** [comment]
perhaps its best to revert the full commit then. i was wondering wtf this split into paintThis and paintThat is trying to achieve.

**Comment by felix-salfelder** [comment]
> perhaps its best to revert the full commit then.

i tried. that doesn't seem easy, conflicts with lots of other stuff.

it seems easiest to fix the interface, and fix #522 afterwards. unless anybody can explain #523.
#522 looks like a boundary box problem, and does not need weird hacks.

**Comment by guitorri** [comment]
Hum. It seams that the direct calls to paintMarkers was needed to sort out the printing, update it maybe? Could be an issue of bounding box, but could also related with current implementation of the rendering loop. See postPaintEvent. Every drawStuff() is added to a list and rendered in order. Maybe, if things are out of order they could be hidden or clipped out during print (even if shown properly on the screen). The above paintMarker hack changes the order on postPaintEvent.

The following is not going to help, but I must mention. 
Direct calls to paint() are not allowed with the QGraphics port. Items do the paint() by themselves.
Similarly ViewPainter is not needed. Just want to mention that all this code has been or is being refactored by me. I will publish the branch once I see the light on the other end. It is mostly working, but I want to keep the noise low and work on my own pace.
What I want to say is, if possible, to hold your horses on matters touching the paint() stuff.

**Comment by felix-salfelder** [comment]
`paintMarkers` does not exist in the element interface. so it does not make sense to call it from the outside. markers are attached to graphs, graphs live within diagrams etcpp.

>  rendering loop

cant fix the rendering loop before fixing the basics.

>  Items do the paint() by themselves.

this sounds promising, thanks for mentioning. in particular that means that we will end up with exactly one "paint" method. close to what i want to achieve with this PR, no?

**Comment by in3otd** [comment]
IIRC, in origin it was a wrong boundary box issue but while fixing that the ability to print a Diagram with or without Markers was added (depending whether the Markers were selected with the Diagram or not) and this led to splitting the `Paint()` method.

**Comment by felix-salfelder** [comment]
so that splitting is only needed internally, right?

(i did not touch it, and i do not have a problem with that)

**Comment by in3otd** [comment]
well, it depends on the exact meaning of "internally"; the Schematic needs to be able to select printing/showing a Diagram with or without Markers.

**Comment by felix-salfelder** [comment]
if somebody wants to hide markers, then (s)he should implement diagram::(un)hideMarkers.

not part of this PR.

**Comment by felix-salfelder** [comment]
or... if markers need to be top-level objects in the schematic, no problem. it does not require paint hacks either.

**Comment by in3otd** [comment]
I've added a couple of commits that fixes the issue with printing and undoes the artificial splitting of `paint()` done some time ago.

**Comment by felix-salfelder** [comment]
marker::isHidden looks weird to me, particularly in public.

why not

    marker::paint(){
         if(hidden()){
              //nop
         }else{
                [paint stuff]
         }
     }

(in addition, flag access must go through function calls)

**Comment by in3otd** [comment]
yep, it's better if `Marker::paint()` decides whether to paint the marker or not.

Regarding the flag access, you mean we should have something like
```
void hide() {hidden = true;};
void unHide() {hidden = false;};
```
in `Marker()`? Seems mostly a style preference to me but, well, this is *your* PR :grin:
(similarly, in the `if` construct above I'll tend to just `return` early instead of putting most of the code in the `else` branch).

**Comment by in3otd** [comment]
code rearranged to let `Marker::paint()` decideswhether to paint the marker or not.

**Comment by felix-salfelder** [comment]
done in refactor branch

**Pull request closed without merging**
