### PR TITLE
Fix for #319 and #320

### PR DESCRIPTION
**Pull request by ra3xdh**
This PR is fix for both #319 and #320 .  Now Up/Down buttons work properly and Frame can be exported to image with Schematic. Please test on your side. Also dropped unused method `Schematic::getSchWidthAndHeight` .

### CODE REVIEW

**Comment by felix-salfelder** [comment]
could you do this the other way around? please fix the "unused method" (which actually was not unused) instead of repeating the code twice?

**Comment by ra3xdh** [comment]
@felix-salfelder , Done as you wish. Duplicate code moved to method.

**Comment by ra3xdh** [comment]
Something strange happened today with Travis. It cannot even start MacOS build. It seems Sourceforge still be down.

**Comment by guitorri** [comment]
I am trying to fix Travis. I is timing out during the Qt install on the OS X...

**Comment by felix-salfelder** [comment]
are you sure that `Schematic::getSchWidthAndHeight` was of absolutely no use? it did a lot more than what you added now. looks like bounding box computation...

apart from that: looks good. please squash the commits before merge, and write a commit message. consider to include an answer to my question please.

**Comment by ra3xdh** [comment]
Squashed commits in one. Indeed `getSchWidthAndHeight()` method was used only for bounding box calculation in `ImageWriter`. You can proof it using "Search of usage" feature of IDEs.

**Comment by guitorri** [comment]
Previously it would take the bounding box of whatever was in the schematic (comps, wires...) now it only takes the size of the frame. Is that right? What if the frame is not set?

**Comment by ra3xdh** [comment]
Yes, all is right. It was tested for schematics with and without frame. All could be exported normally. Here is an example without frame:
export
And with frame:
export-fr

**Comment by guitorri** [comment]
Thanks!

**Comment by in3otd** [comment]
...too fast @guitorri, IMHO.
As expected, now the exported image is limited to the frame boundaries, if a frame is present. But if there are components outside the frame, those will not be printed.
Sure, it's normally a user error to have components placed outside a frame, but I do not see why we should silently ignore those components. When we do a "View all" in the schematic, all the components are shown, inside or outside a frame and this is of course the Right behavior. Same for netlisting, we do not care if a frame is there, we netlist all the components, as the schematic is composed of all the components, inside or outside the frame, which is just a graphical decoration.

So I will strongly suggest to have all components printed as shown on the screen, inside or outside a frame. If the user has mistakenly placed components outside a frame, this mistake should be shown in the printed output.
If we would like to be even more flexible, add a "limit print to frame boundaries" option, but this should not be the default behavior.

**Comment by felix-salfelder** [comment]
@in3otd thank you! i couln't find the place where the bounding box computation is actually required...

>  I will strongly suggest to have all components printed

seconded

**Comment by ra3xdh** [comment]
See #331 for fix

**Pull request merged**
