### PR TITLE
Add 4 new modules(ohmmeter,wattmeter,fasor diagram and temporal diagr…

### PR DESCRIPTION
**Pull request by FoxMarts**
…am for AC)

### CODE REVIEW

**Comment by in3otd** [comment]
A more detailed description of what this PR does would be helpful, or actually needed; I guess this is somewhat related to #395, #396, #398, #440, #441.
Examples showing how to use these new components will also be helpful.

As you saw, the PR could not be built by Appveyor and Travis, so there is little chance that others can build and test it. The main error seems to be `Cannot find file 'bitmaps/ohm.png'`; you probably forgot to commit that file.

You have included lot of stuff that was already merged in the `develop` and/or `release-0.0.19` branches and has nothing to do with the new components you added. Please remove those changes and rebase your changes on the `develop` branch.
Included there are several files which are generated by the `bootstrap` script, also those should be removed.

If you have question on how to reshape this PR and/or use `git` feel free to ask here; you can also often find someone on the channel `#qucs` on [freenet](https://webchat.freenode.net/) that should be able to help

**Comment by guitorri** [comment]
I can give you the context for this. 

These modules were written by students of ISEP in Portugal under the guidance of Prof. Mario Alvez. I was contacted by them to help including the modules in QUCS, but in the current state is not really possible. The students seem to have difficulties with Git.

Some examples for these modules can be found in the following document.
[Exemplos.pdf](https://github.com/Qucs/qucs/files/581588/Exemplos.pdf)

Some time ago Pedro @Pedro-project tried to submit the wattmeter, see #389, #395, #396, #440, #441. It seems he was unable to rebase the code.

I tried to assist them and cleanup the code. I did that, but I did not perform any sort of test:
https://github.com/guitorri/qucs/tree/pedro-code

@FoxMarts, my suggestion is to take the above branch as base an apply the changes one by one.

**Comment by ra3xdh** [comment]
I see, it is a duplicate of #682. Should it be closed after #682 is merged?

**Comment by andresmmera** [comment]
I think so. PR 682 was merged last sunday so it makes no sense having this PR opened. Can someone close this one? I can't closing it from the github app

**Comment by ra3xdh** [comment]
Closing this after #682 is merged.

**Pull request closed without merging**
