### PR TITLE
Fixes for building on Windows

### PR DESCRIPTION
**Pull request by in3otd**
**This is still a WIP - do not merge yet**

This fixes some issues on Windows. I am still checking if there is more to do there but opened the PR in case others are playing with Windows.

### CODE REVIEW

**Comment by guitorri** [comment]
Can we just revert dc93970d7 for the moment? This is breaking the build on Windows.

**Comment by in3otd** [comment]
ok, either revert it or cherry-pick 1da108877b1e09bddc8382610055d9c5fe5ea3fc above. I've run `qucs-test` on that and saw no issue. You will likely need also f99ec6743b33b76729d8f1fc4b277c175d4c1e6e if you install Qucs in a path with spaces in it to be able to run `qucsator` and the othe tools

**Comment by guitorri** [comment]
Or we can cherry-pick the [cmake] fixes from https://github.com/Qucs/qucs/compare/WIP-appveyor-support into this Windows related PR.

Doing so we should be able to kick-off an automated Appveyor Windows build.

**Comment by guitorri** [comment]
I will add my patches to yours and open another PR.

**Comment by guitorri** [comment]
See PR #299

**Comment by in3otd** [comment]
ok, my commits were maybe lacking some comments, but apart from that they should be fine :grin:

**Pull request closed without merging**
