### PR TITLE
Fix Qt4 removal from MSYS2 packages

### PR DESCRIPTION
**Pull request by in3otd**
...trying a "fix" from [here](https://github.com/slowphil/texmacs-win-builder/issues/3).

### CODE REVIEW

**Comment by in3otd** [comment]
Just noticed that the [Appveyor docs](https://www.appveyor.com/docs/build-cache/) say that "*By default, saving cache is disabled in Pull Request builds.*", so it seems we need to have this merged before having a valid cache.

**Comment by in3otd** [comment]
ok, it seems to work.
Someone please press the *Merge* button - or I'll do that later :grin:.
Not sure this should go to `master` now, as there are other small things that should be merged in `develop`, so maybe we can merge `develop` into `master` later.

**Comment by guitorri** [comment]
Only releases branches should merge back into master. 
I will give another try on finishing off release 20.

**Comment by in3otd** [comment]
thanks.
yes, but I wonder(ed) if also #953 and #951 (and #946, assuming I'll be able to finish it soon) should be included in 0.0.20.

I was also taking a look at how to do the release, cross-compiling for Windows in Linux - but I'll need quite some time to set up everything and I'm not sure I'll be able to make it work.

**Comment by guitorri** [comment]
Sure, tag them for 20. After they are in, we release it.

**Pull request merged**
