### PR TITLE
Travis check03

### PR DESCRIPTION
**Pull request by oxmon-2500**
python 3.6

### CODE REVIEW

**Comment by guitorri** [comment]
Nice. Thank you.
Can I merge https://github.com/Qucs/qucs-test/pull/36?
Then you can update the submodule to sync with the master branch of qucs-test.

**Comment by oxmon-2500** [comment]
Hi, yes python migration is final. Pls merge it

**Comment by guitorri** [comment]
Done. 
Please update the qucs-test submodule and push again to this PR.

**Comment by in3otd** [comment]
uh, why Travis didn't run here??

**Comment by guitorri** [comment]
Not sure why Travis didn't build. 

@oxmon-2500, merging qucs develop branch into your PR is not what you want.
You want to update qucs-test submodule on qucs develop branch and keep your fixes done on .travis.yml

Something like:
 ```
cd ~/git/qucs
git checkout develop
git pull origin develop #update develop
git checkout -b test-python3 # new branch
cd qucs-test
git pull origin master
cd ..
git add qucs-test
git commit -m "update qucs-test to python3"
git cherry-pick  3adb88e # fixes to .travis.yml
# push and force update your branch and this PR
git push -f [oxmon-remote-name] test-python3:travisCheck03
# or just push test-python3 to your fork and create another PR
```
Let me know if you wan't me to do this for you.

**Comment by oxmon-2500** [comment]
> Not sure why Travis didn't build.
> 
> @oxmon-2500, merging qucs develop branch into your PR is not what you want.
> You want to update qucs-test submodule on qucs develop branch and keep your fixes done on .travis.yml
> 
> Something like:
> 
> ```
> cd ~/git/qucs
> git checkout develop
> git pull origin develop #update develop
> git checkout -b test-python3 # new branch
> cd qucs-test
> git pull origin master
> cd ..
> git add qucs-test
> git commit -m "update qucs-test to python3"
> git cherry-pick  3adb88e # fixes to .travis.yml
> # push and force update your branch and this PR
> git push -f [oxmon-remote-name] test-python3:travisCheck03
> # or just push test-python3 to your fork and create another PR
> ```
> 
> Let me know if you wan't me to do this for you.

OK, I think it is better if you do this. My experience with git is growing but still far from perfect :-)
I will analyse the above approach carefully and learn more

**Comment by guitorri** [comment]
Travis did not run because there was a typo in the .travis.yml file. If failed to parse.
Your patches are now moved to #964.

**Pull request closed without merging**
