### PR TITLE
integrate qucs tests into qucs package

### PR DESCRIPTION
**Pull request by felix-salfelder**
currently some tests are not included with qucs. including these tests will increase test coverage.

with this, `make check` will run all tests we have, not just few of them.

### CODE REVIEW

**Comment by felix-salfelder** [comment]
almost...

    Warning: QucsConv not found:  "qucsconv" 
    Error: Could not prepare the netlist...
    Critical: "ERROR: Cannot load library component "D1"." 

can you merge #376? i'd like to not mix it up.

**Comment by felix-salfelder** [comment]
@guitorri some tests don't pass on osx (I stumbled upon the extra skiplist). this is unexpected. can you point me to the reason for this?

**Comment by felix-salfelder** [comment]
> All checks have passed

hey, with this, we could finally produce release candidate tarballs...

@guitorri i have tentatively removed the coverage thing. may I suggest to compute coverage only for the `develop` branch? this will cut the check run time for PRs. and also introduce a place where we could add more checking/snapshotting/profiling of any duration we might want to have some day.

**Comment by guitorri** [comment]
This is looking good. :+1: 

With respect o the skipped tests. See #205 for some more details. There are platform dependency issues in the transient code or components. 

About coverage. We could have branches specialized for each task. Coverage, static analysis, packaging, doxygen, nightly builds... sure. The .travis.yml grew as I managed to hook more stuff in it. Perhaps it is time to clean it up.

I agree, perhaps is not necessary to check coverage on each PR.

The wget patch 8765e8d  is really about Googletest integration (I still don't get what you mean by software distribution...). The reason why I put it into the configure (as an option) was to facilitate the download and compilation. It is supposed to be compiled along with the same flags as the rest of the code. If enable it runs with `make check`, adding more unit tests. I know GoogleTest is currently underutilized, but it might come in handy when crafting unit tests to cover corner cases that are hard to reach. Alternatively we could the code it into the repository, but for some reason I forgot I did not include at that time.

I will try to find some time tomorrow to kick the tires of this PR.

**Comment by felix-salfelder** [comment]
> about coverage. We could have branches specialized for each task. Coverage, static analysis, packaging, doxygen, nightly builds... sure. The .travis.yml grew as I managed to hook more stuff in it. Perhaps it is time to clean it up.

i will/might start/experiment with a develop branch. i am not yet fully familiar with the travis thing. lets add/reassign tasks to other branches as it seems appropriate.

> The wget patch 8765e8d is really about Googletest integration (I still don't get what you mean by software distribution...).

in my understanding. a *distribution* is something that puts together and delivers *packages*. qucs is one such package. imo it should not try to process other packages.

NB: i am aware of the ADMS "sub"package, i consider this a leftover from times without an ADMS release tarball. or should we also ship a kernel a shell and a c++-compiler...? (imo: no. others are truly better at this).

> facilitate the download and compilation.

wget in configure is clearly beyond the scope of the configure program. configure is originally meant to create makefiles (+ related things) --  and this is what the user expects it to do (least-surprise-stuff...). note that the wget command leaks user data, and can fail if there's a firewall. let me suggest to turn the wget block into something like the following.

    if $something
      AC_MSG_ERROR([not found. consider running get-$packagename.sh to fetch from $somewhere])
    fi

to reduce the surprise factor. i don't insist on removing them `:)`.

**Comment by felix-salfelder** [comment]
this seems to be working as intended now..

**Comment by guitorri** [comment]
Looking good! Is there anything else you want to do here? 

Yesterday I was about to merge this. 
I got some issue with `make distcheck` (dist and check worked), related to `qucs-core\tests\basic`. I will try to reproduce.

**Comment by felix-salfelder** [comment]
> Looking good! Is there anything else you want to do here?

no. that's it. note that this is actually 3 PRs. when in doubt, merge the others first.

> I got some issue with make distcheck (dist and check worked), related to qucs-core\tests\basic. I will try to reproduce.

thanks. yes -- lets fix issues first, let me know the details.

yesterday, after I merged master, something strange happened (see bd822ea for the workaround). if you have an idea, lets properly fix this as well.

**Comment by guitorri** [comment]
I saw that this includes #361 and #387. I am OK with merging this PR. I also want to see if GitHub will close the intermediate PRs.

The distcheck issue I mentioned did not surfaced again. 

I have two small patches to send later. One includes to distdir some pdf figures needed by qucs-doc. If I try to extract and build the tarball made run `make dist` in another location latex complains about missing figures.

The `qucs-test/.git/` directory is also being copied into distdir. Yes, we need to improve this later.

I will merge this and we work from there. 

Thank you so much!

**Pull request merged**
