### PR TITLE
add Wno-deprecated-register C++flags

### PR DESCRIPTION
**Pull request by yodalee**
disable noisy warning

### CODE REVIEW

**Comment by guitorri** [comment]
I restarted Travis. For some reason the ADMS tarball was not available (SF down?)... Building again

**Comment by yodalee** [comment]
Passed, maybe SF issue lolololol

**Comment by guitorri** [comment]
Looks good to me.

**Comment by in3otd** [comment]
...when compiling with `clang` (`clang version 3.3 (tags/RELEASE_33/final)`) I now get a lot of

````
warning: unknown warning option '-Wno-deprecated-register'; did you mean '-Wno-deprecated'? [-Wunknown-warning-option]
````

which version are you using ??

**Comment by yodalee** [comment]
My version is clang 3.5, I think this option is added in llvm v3.4, so version 3.3 won't accept this.

**Comment by guitorri** [comment]
The MinGW g++ also warns about unknown option. We might need to add the flag selectively by compiler. 

On qucs-core the parser generated by bison also uses the `register`. 
I gave it a try to silence the wanings with pragmas, see my [clang-register-warning](https://github.com/guitorri/qucs/commit/98e43f2636e4686e170d8c3c48203e318335e3e7). I forgot why I did not merge this...

However the register warnings are coming from Qt, so the pragma may not help here...

Shall we reopen and rename #154 and so we don't forget it?

**Comment by yodalee** [comment]
I think we can open a new issue to handle this. The discussion in 154 is mostly about C++11, not register issue ( which is came along with clang version > 3.4 with Qt, not c++)

**Pull request merged**
