### PR TITLE
qt4/5 WIP

### PR DESCRIPTION
**Pull request by felix-salfelder**
Eduards commits based on Guilhermes q3scrollview rework

in combination this should do the switch from qt3/4 to 5

this needs work. feel free to push to this branch

### CODE REVIEW

**Comment by guitorri** [comment]
Hold on. I was doing the same thing. I also merged develop on top of everything. Cleaning up merge fuzz and making sure it still builds with Qt4 or Qt5.

**Comment by felix-salfelder** [comment]
On Thu, Jul 05, 2018 at 02:37:42PM -0700, Guilherme Brondani Torri wrote:
> Hold on. I was doing the same thing. I also merged develop on top of
> everything. Cleaning up merge fuzz and making sure it still builds
> with Qt4 or Qt5.

we should rebase this to develop.

it will be much harder to cleanup if there are merges in between.

i have squashed several back-and-forth edits already...

**Comment by felix-salfelder** [comment]
On Thu, Jul 05, 2018 at 02:37:42PM -0700, Guilherme Brondani Torri wrote:
> Hold on. I was doing the same thing. I also merged develop on top of everything. Cleaning up merge fuzz and making sure it still builds with Qt4 or Qt5.

i did only touch Eduards commits, so if you rebased yours to develop, i
can put his on top again...

thanks

**Comment by guitorri** [comment]
Hum. I was not planning on rebasing my branch on `develop`. What I dit was to rebase `removing-qt3` and merge `develop` onto my branch. See https://github.com/guitorri/qucs/tree/removing-qt3-rebase-merge-develop
I am afraid there will be a lot of fuzz if I rebase on `develop`. I will give it a try to see if it is worth it.

**Comment by felix-salfelder** [comment]
On Sun, Jul 08, 2018 at 01:54:24PM -0700, Guilherme Brondani Torri wrote:
> Hum. I was not planning on rebasing my branch on `develop`. What I dit was to rebase `removing-qt3` and merge `develop` onto my branch. See https://github.com/guitorri/qucs/tree/removing-qt3-rebase-merge-develop
> I am afraid there will be a lot of fuzz if I rebase on `develop`. I will give it a try to see if it is worth it.

yes please.

'removing-qt3' was not ready, see my rewrite.

**Comment by guitorri** [comment]
Rebased branch: https://github.com/guitorri/qucs/tree/QG-port-13-rebase
I squashed a few things on my side. There are a few more to do, but I need to split some commits. Maybe later.

What about creating a feature branch on the main repo? I really don't want this merged into develop at this early stage.

**Comment by felix-salfelder** [comment]
On Wed, Jul 11, 2018 at 08:26:58AM -0700, Guilherme Brondani Torri wrote:
> I am squashing what I can. I will soon move this to the main repo.

thanks. still trying to figure out what's wrong with travis here. "make
distcheck" works for me ..

please merge #806 and #807 before the next rebase.

**Comment by felix-salfelder** [comment]
On Thu, Jul 12, 2018 at 01:26:24AM -0700, Guilherme Brondani Torri wrote:
> guitorri commented on this pull request.
> 
> 
> 
> > @@ -190,18 +190,13 @@ if ! `$PKG_CONFIG --atleast-version=4.6.0 QtCore`; then
>     AC_MSG_ERROR([Qt >= 4.6.0 is required.])
>  fi
>  
> -UIC=`$PKG_CONFIG --variable uic_location ${qt_name}Core`
> -MOC=`$PKG_CONFIG --variable moc_location ${qt_name}Core`
> -RCC=`$PKG_CONFIG --variable rcc_location ${qt_name}Core`
> +# this seems to work for both Qt4 and 5
> +RCC_=`$PKG_CONFIG --variable rcc_location ${qt_name}Core`
> 
> For some reason, on OSX the `rcc_location` variable  (and others) are not defined on the Qt5Core.pc file (Qt5.11.1)

hmm. everybody uses pkgconfig these days. i would like to stick to it.
the QT_DIR hacks break down completely if i want to select a specific
Qt (which i think is what we want...?).

> Can't we set the `uic`, `moc` and `rcc` relative to `QT_DIR`?

i think so. there is a `*darwin* )` in line 363.
if QT_DIR works on OSX...
(for now) you could set MOC_ to "$QT_DIR/moc" and ignore what pkg-config
proposes.

this will likely break Qt selection on OSX, hence ideally, we should
find a way to always rely on pkgconfig, remove the host_os switch.
pkgconfig seems to be the preferred method out there. I suspect that
this is also how CMake does it (no?).

NB: it was a pain to make it work for both Qt4 and 5. and it's not ready
yet, -fPIC, and some -l are missing for Qt5. (The Qt version is checked
but not used yet.)

PS: is this purely a Qt5 issue? how does "develop" play with OSX?

**Comment by felix-salfelder** [comment]
On Thu, Jul 12, 2018 at 01:26:24AM -0700, Guilherme Brondani Torri wrote:
> guitorri commented on this pull request.
> 
> 
> 
> > @@ -190,18 +190,13 @@ if ! `$PKG_CONFIG --atleast-version=4.6.0 QtCore`; then
>     AC_MSG_ERROR([Qt >= 4.6.0 is required.])
>  fi
>  
> -UIC=`$PKG_CONFIG --variable uic_location ${qt_name}Core`
> -MOC=`$PKG_CONFIG --variable moc_location ${qt_name}Core`
> -RCC=`$PKG_CONFIG --variable rcc_location ${qt_name}Core`
> +# this seems to work for both Qt4 and 5
> +RCC_=`$PKG_CONFIG --variable rcc_location ${qt_name}Core`
> 
> For some reason, on OSX the `rcc_location` variable  (and others) are not defined on the Qt5Core.pc file (Qt5.11.1)
> Can't we set the `uic`, `moc` and `rcc` relative to `QT_DIR`?

possible better idea. note that in

AC_PATH_PROGS(MOC, $MOC_ moc, :, $QT_BINPATH:$PATH)

the $MOC_ variable can be empty. and actually this is happening here for
some choice of Qt.  in that case, it only looks for the alternative
("moc") in $QT_BINPATH:$PATH. so
1) it always works if moc is installed.
2) it works if moc is present in QT_BINPATH.

so if pkgconfig fails to deliver QT_BINPATH on OSX, it might make sense
to just set QT_BINPATH, (inferred from QT_DIR?), in the darwin block and
let AC_PATH_PROGS sort out the rest.

**Comment by guitorri** [comment]
I created the branch https://github.com/Qucs/qucs/tree/qt5

Perhaps you can PR your latest patches over there and close this one?
I will try fix/enable CMake instances in the mean time.

**Comment by felix-salfelder** [comment]
rebased. it seems possible to retarget as well, so i just keep going with this PR.

**Comment by felix-salfelder** [comment]
Running [qucs]:  qucs -n -i testsuite/AC_SW_resonance_prj/resonance.sch -o testsuite/AC_SW_resonance_prj/test_resonance.txt
    Return code:  139

somethings wrong with the tests. i wonder if that error message is really the problem...

**Comment by guitorri** [comment]
The error is coming from `qucs`. I am not sure the `save schematic` function is working properly in the qt5 branch at the moment.
Maybe disable the qucs-tests for a while?

**Comment by felix-salfelder** [comment]
On Fri, Jul 13, 2018 at 02:40:56AM -0700, Guilherme Brondani Torri wrote:
> The error is coming from `qucs`. I am not sure the `save schematic`
> function is working properly in the qt5 branch at the moment.  Maybe
> disable the qucs-tests for a while?

digging into this.

i think the earlier i can fix this, the better... also found a bug in
develop that i need to deal with first.

**Comment by felix-salfelder** [comment]
this is close. the netlist test is failing, still.

**Comment by felix-salfelder** [comment]
irrelevant, done in #840

**Pull request closed without merging**
