### PR TITLE
Fix in qucs-activefilter

### PR DESCRIPTION
**Pull request by ra3xdh**
This  PR contains fix to avoid infinite loop at some active filter input parameters.

### CODE REVIEW

**Comment by yodalee** [comment]
@ra3xdh can you squash these two commits?
and btw @guitorri the coverage test is still under testing right, so we can merge this PR even coverage test fail?

**Comment by ra3xdh** [comment]
Megred two commits. See #212

**Comment by guitorri** [comment]
@yodalee there is no coverage for the Qt part, only for qucs-core. Anyway, last time I set Coveralls not to comment on the PR. They must have changed something. I will take a look.

**Comment by yodalee** [comment]
Oh, actually you don't need open another PR. Just squash the commits then push the branch with `-f` (forced update) flag.

**Pull request closed without merging**
