### PR TITLE
Marker

### PR DESCRIPTION
**Pull request by felix-salfelder**
cleanup related to marker code

### CODE REVIEW

**Comment by in3otd** [comment]
can you please provide some context? Are you "just" cleaning-up the code or preparing for adding new features? I saw you added some commits after opening the PR, this is ok, just let us know if you plan to continue working on this branch and when it is ok to be merged. Otherwise someone might merge it before you finish working on it (improbable, but...).

Besides, 06fcb000ca88d3ce28ba6520d92ef95ff95a5995 should be squashed with 76656a6afd93f74e704b5bc6002f922edceb83b0, there is no reason to have it in the master commits history.

**Comment by felix-salfelder** [comment]
> can you please provide some context?

the marker code is entangled with the internals of the 'dat' file backend. my rough plan is to first make the diagram code independent of the data source, then enable support for other file formats and data sources.

the branch is ready for merge as soon as you agree with the changes. the commits added after the PR seemed to fit, so i moved them here, please consider these a part of the PR.

> Besides, 06fcb00 should be squashed with 76656a6, there is no reason to have it in the master commits history.

it's already published in the marker branch. are you suggesting to rewrite history (evil?), or do you prefer a pull request on a new branch (losing context)?

thank you

**Comment by in3otd** [comment]
Thanks for details, I think it's good to know which are the (rough) plans behind PRs, in case someone else is thinking to work in the same area.

As said, IMHO it's perfectly ok to add commits after a PR, in some cases might even be advisable (e.g. when looking for feedback halfway during some particular development), just it need to be known that it is still a WIP otherwise we will assume the PR is finished and ready to be merged, from the developer point of view.

About rewriting history, there are lot of opinions around telling that *rewriting history is always evil*: IMHO, rewriting history for a topic branch, used just for a PR, is perfectly fine. It is a short-lived branch and it is not meant to be widely shared. In the ideal case, all the commits in a PR end up verbatim in the project master branch, so I think it is more important to (try to) have an easy to read history there. Keeping trace of small corrections of commits done in the same branch does not aid readability for someone trying to track down the changes in the future. Other opinions are welcome ( @guitorri ? )

**Comment by felix-salfelder** [comment]
> Keeping trace of small corrections of commits done in the same branch does not aid readability for someone trying to track down the changes in the future.

this gets a bit complicated. how is guitorri (who has kindly examined this PR) supposed to not start all over again, once i rewrote the branch history? how could I have asked, if 06fcb00 fixed the problem he reported, if 06fcb00 did not even exist?

i think i will stick to not rewriting history. please reject the PR, if you consider the history too messy, or just squash/fix the commits just before the merge.

thanks

**Comment by nvdl** [comment]
Or possibly you can clone this branch and squash that to create the PR.

**Comment by in3otd** [comment]
sorry, today seems to be my rant day. @guitorri, if you examined this and saw something to be corrected, wouldn't have been better to leave a comment, so others know of the status??

As I see it, the flow should have gone like this:
- you opened the original PR
- a reviewer told you that something needed to be corrected
- you correct it (in this case 06fcb000ca88d3ce28ba6520d92ef95ff95a5995)
- the reviewer check your changes and tells you that now everything is ok and you should squash some commits
- you squash 06fcb000ca88d3ce28ba6520d92ef95ff95a5995 with 76656a6afd93f74e704b5bc6002f922edceb83b0 (note that it's not trivial, since there is a commit in between)
- at this point the reviewer has two choices
  - it reviews again, to verify it still works ok (personally I'll do that)
  - it trusts you and merges the PR
  - (a third way, may be for the reviewer to keep his local copy of your original PR and compare that the final result is the same as the new, squashed, PR)

Yes, this is more work for the reviewer, the price to pay for a cleaner history.

Surely I will **not** reject the PR just because one commit that IMHO should have been squashed was not, the Qucs history has seen worse and the most important consideration is the code correctness.

Since @guitorri  is apparently working on this, I let him do the merge. Also because I did not actually check the code, just looked at the changes...
If I had to do it, I *might* have merged the commit locally, depending if I had some spare time or not (as said, it's not entirely trivial)

**Comment by guitorri** [comment]
@in3otd, yes I should have said here that I found an issue on this PR. I mentioned it to @felix-salfelder privately along with other comments.

I am OK with rewriting history on a feature branch related to a PR. It may happen that one accidentally push an unrelated commit. One can always open a new PR with a cleaned up branch and reference the old, but as said above, keeping the PR context/comments might be helpful sometimes. I don't see a problem in squash/rebase and force push to update a PR.

Branches living on the project repository should never be rewritten.

If I have issues to ckeck/pull a modified branch I just delete it and pull it anew. 

I will review this again.

**Comment by guitorri** [comment]
Looks good to me. Thank you!

**Pull request merged**
