### PR TITLE
add qucs-core/tests/testDefine.h to EXTRA_DIST

### PR DESCRIPTION
**Pull request by felix-salfelder**
at home, i need this header to pass the tests.

i wonder, how the distcheck on travis passed...

### CODE REVIEW

**Comment by guitorri** [comment]
I wonder how it also passed on my Mac.

**Comment by felix-salfelder** [comment]
ok, i think i do know.

lets see, what happens.

**Comment by felix-salfelder** [comment]
hmm, the usual sourceforge trouble...

**Comment by guitorri** [comment]
You should be able to rerun AppVeyor. I added the team of Github Collaborators into AppVeyor/Travis. just login with your Github credentials int Appveyor and let me know...

**Comment by felix-salfelder** [comment]
i have logged in to appveor, can't seem to find the 'rerun' button. anyway, i just rewrote the last commit...

**Comment by guitorri** [comment]
Well, to be correct it should be either 'new build' or 're-build pr' to the left of the 'download log' button.

**Comment by felix-salfelder** [comment]
there's a 'download log' button, but nothing else. (the login was successful though).

**Comment by guitorri** [comment]
@in3otd is there something else you did to be able to restart the builds on AppVeyour? Felix is not being able to do that.

**Comment by in3otd** [comment]
no, nothing special, except logging out and in again. But this should not be the issue, since he just logged in...

**Comment by in3otd** [comment]
...I forgot, @felix-salfelder when you log in to AppVeyor, do you see a selection box named "Account" on the left? There you should select "qucs" and not your username.
If you do not see the Account selection box, something is wrong with the access permissions (I did not see it before guitorri added the Qucs team to AppVeyor)

**Comment by felix-salfelder** [comment]
now i tried a third time and a "cancel build" button appeared. i think that is it.

weird. but thanks!

**Pull request merged**
