### PR TITLE
Setup Transifex for Qucs desktop aplications

### PR DESCRIPTION
**Pull request by guitorri**
I created an project Transifex to ease the translation management for Qucs:
https://www.transifex.com/qucs/qucs-desktop/

Subscribers to this free (for open-source) service enjoy of a very nice web interface to do localization. It offers features like translation memory and machine translation (provided by Bing Translator).

This PR incorporates some changes to accommodate the service. 

It also updates several translation files, some entries where automatically translated (100% match agains the translation memory) others where translated manually or semi-automatically by volunteers already subscribed to our project in Transifex.

I am working on the documentation to add to the Wiki.

This includes a partial fix for issue #256

### CODE REVIEW

**Comment by ra3xdh** [comment]
This PR also fixes #353.  @denizzzka, Please test also on your side. I think it could be merged.

**Comment by denizzzka** [comment]
> This PR also fixes #353. @denizzzka, Please test also on your side. I think it could be merged.

Confirmed, #353 fixed by this PR

**Comment by guitorri** [comment]
Thanks. I will merge then I can push the source strings to Transifex once again...

**Comment by ra3xdh** [comment]
@guitorri  We are getting to 0.0.19 release, It seems all critical bugs are fixed. May I make the final rebase of my `rebase_spice4qucs` branch now to prepare final `Qucs-S` packages.

**Comment by guitorri** [comment]
@ra3xdh I will try to cleanup the milestones for 0.0.19. 
Indeed, (known) critical issues are cleared. Please take a look at the remaining issues and see if we should move them to 0.0.20.

**Comment by ra3xdh** [comment]
@guitorri I have found another forgotten critical bug: #247 . It still present in `master`
I think, all other issues, maybe except #310 and #300 could be moved to 0.0.20.

**Pull request merged**
