### PR TITLE
Fix qucshelp

### PR DESCRIPTION
**Pull request by guitorri**

### CODE REVIEW

**Comment by in3otd** [comment]
closed by mistake, sorry

**Comment by in3otd** [comment]
seems to work, but when running `qucshelp` I get a message `QCoreApplication::applicationDirPath: Please instantiate the QApplication object first` on the console.

**Comment by in3otd** [comment]
BTW, is the menubar working in `qucshelp` there? Here it doesn't work, apparently something went wrong [here] (https://github.com/Qucs/qucs/commit/03090ed544ab59a44cddc4e368161279e413bc54#diff-c8abfad56746b86fe9819f1141e7eb2e)

**Comment by guitorri** [comment]
I think it is fixed now.

**Comment by in3otd** [comment]
Works now, thanks.

While you are there, could you please add `optimization9.png` and `optimization10.png` to the list of files in [`qucs-help/docs/en/Makefile.am`] (https://github.com/Qucs/qucs/blob/master/qucs/qucs-help/docs/en/Makefile.am) and [CMakeLists.txt] (https://github.com/Qucs/qucs/blob/master/qucs/qucs-help/docs/en/CMakeLists.txt) as I have forgotten that when doing 43205e2ea48c3e40ffb44c4ab6cb082049393668 some time ago, so those pictures are not installed, thanks... :disappointed: (seems not worth a separate PR)

**Comment by guitorri** [comment]
Merged into `release-0.0.19` branch (879c4cfe9772b60b954ab095b6b9f6e3c65761e3)

**Pull request closed without merging**
