### PR TITLE
Issue 300

### LINKED ISSUE #300: QucsActiveFilter results on Windows
When running `QucsActiveFilter` with the default parameters, I get different results on Linux and Windows.

To reproduce:
- open the `QucsActiveFilter` tool
- press the button `Calculate and copy to clipboard` (i.e. leave all the parameters at the default)
- on Linux it runs fine. On Windows it fails

This is the output of the Filter Calculation Console:

- On Linux:
````
Filter order = 14

Poles list Pk=Re+j*Im
-0.111964 + j*0.993712
-0.330279 + j*0.943883
-0.532032 + j*0.846724
-0.707107 + j*0.707107
-0.846724 + j*0.532032
-0.943883 + j*0.330279
-0.993712 + j*0.111964
-0.993712 + j*-0.111964
-0.943883 + j*-0.330279
-0.846724 + j*-0.532032
-0.707107 + j*-0.707107
-0.532032 + j*-0.846724
-0.330279 + j*-0.943883
-0.111964 + j*-0.993712

Part list
Stage# C1(uF) C2(uF) R1(kOhm) R2(kOhm) R3(kOhm) R4(kOhm)  R5(kOhm) R6(kOhm)
     1    62.680pF 10000.000pF   284.295   284.295   142.148     0.000     0.000     0.000
     2   545.421pF 10000.000pF    96.376    96.376    48.188     0.000     0.000     0.000
     3  1415.291pF 10000.000pF    59.829    59.829    29.915     0.000     0.000     0.000
     4  2500.000pF 10000.000pF    45.016    45.016    22.508     0.000     0.000     0.000
     5  3584.709pF 10000.000pF    37.593    37.593    18.797     0.000     0.000     0.000
     6  4454.579pF 10000.000pF    33.723    33.723    16.862     0.000     0.000     0.000
     7  4937.320pF 10000.000pF    32.032    32.032    16.016     0.000     0.000     0.000

Filter calculation was sucessfull
````
- on Windows
````
	

    Filter order = 14
     
    Poles list Pk=Re+j*Im
    -0.111964 + j*0.993712
    -0.330279 + j*0.943883
    -0.532032 + j*0.846724
    -0.707107 + j*0.707107
    -0.846724 + j*0.532032
    -0.943883 + j*0.330279
    -0.993712 + j*0.111964
    -0.993712 + j*-0.111964
    -0.943883 + j*-0.330279
    -0.846724 + j*-0.532032
    -0.707107 + j*-0.707107
    -0.532032 + j*-0.846724
    -0.330279 + j*-0.943883
    -0.111964 + j*-0.993712
     
    Part list
    Stage# C1(uF) C2(uF) R1(kOhm) R2(kOhm) R3(kOhm) R4(kOhm)  R5(kOhm) R6(kOhm)
         1    62.680pF 10000.000pF       nan       nan       nan     0.000     0.000     0.000
         2   545.421pF 10000.000pF       nan       nan       nan     0.000     0.000     0.000
         3  1415.291pF 10000.000pF       nan       nan       nan     0.000     0.000     0.000
         4  2500.000pF 10000.000pF    45.009    45.009    22.511     0.000     0.000     0.000
         5  3584.709pF 10000.000pF       nan       nan       nan     0.000     0.000     0.000
         6  4454.579pF 10000.000pF    33.717    33.717    16.865     0.000     0.000     0.000
         7  4937.319pF 10000.000pF    32.026    32.026    16.019     0.000     0.000     0.000
     
    Filter calculation terminated with error
````

any idea ?

### PR DESCRIPTION
**Pull request by in3otd**
This fixes #300.
Actually the fix is just the first commit, 08e0e70f8287316f373e70461b86b327594d83b5, the others are just small fixes here and there. The last one, 3b42993761ad6b535d87909ac1f60b3acf7f3e90 , changes a bit the window layout to make it more compact, Looks nicer to me, YMMW, leave it out if you prefer.

Some general notes, for future developments:
- maybe it would have been better to use `double` instead of `float` to hold the intermediate results (poles/zeros, etc.), this might have avoided the numerical errors above (did not actually try)
- in [`mfbfilter.cpp`] (https://github.com/Qucs/qucs/blob/master/qucs/qucs-activefilter/mfbfilter.cpp#L284) it will be nice to have `C1` and `C2` set to the nearest `E12` or `E24` value
- I saw that it is normally recommended to arrange the stages starting from the first-order section (if existing) then proceed from the lowest Q section to the highest Q one (see e.g. [here] (http://www.ti.com/lit/an/sloa049b/sloa049b.pdf), page 8). The program at present builds the complete filter in the inverse order. Of course it does not make any difference in simulation, but might make in practice.

### CODE REVIEW

**Comment by in3otd** [comment]
...oops, forgot to add the pixmap icon file, will correct later.

**Comment by in3otd** [comment]
@guitorri the `OS X` build failed with
```
Error: SHA1 mismatch
Expected: 578cd173302725429e3982d70a0e2be335e27d40
Actual: ea60df615387f47bdfdfe4da48f6567c4ec60f74
Archive: /Library/Caches/Homebrew/adms-2.3.4.tar.gz
```
do you know what could be the reason?

**Comment by guitorri** [comment]
Corrupted download I would say. SourceForge is a bit unreliable. I restarted the OS X instance.

**Comment by ra3xdh** [comment]
@in3otd , Thank you for this fix! All looks good. But new main window don't fit in notebook screen (1366x768):
new_actfilt

**Comment by in3otd** [comment]
thanks ra3xdh. I guess I should reduce the vertical space allocated for the transfer function and enlarge the one for the schematic. It seems the schematic is taking up more vertical space than the input boxes on the right. My original intention was to have the vertical size determined by the controls on the left side and resize the images on the right side to fit, but seems it is still not working properly.

**Comment by in3otd** [comment]
one more thing, that can also explain the increased vertical size: I have aligned the usage of `QucsSettings` to what is done in the other applications of the Qucs suite: the language and font size to use are read from the common settings storage. So now the application has a slightly larger font size, at least on my system and I suspect this might be the case also on yours.

**Comment by in3otd** [comment]
Added patch from ra3xdh to use `double` instead of `float` and implemented the possibility to hide/show the text output console showing the calculation details at the bottom of the window, so that it can be made to fit on smaller screens. Hidden/visible status is remembered across sessions using `QSettings`.

**Comment by ra3xdh** [comment]
@in3otd, Console hiding feature looks good. But in some cases large vertical gaps between GUI controls remains at application start. I cannot to determine a proper step sequence to reproduce this. I have added force window resizing in `QucsActiveFilter` class constructor. See https://github.com/in3otd/qucs/pull/2 Now all resizing bugs should gone. I think this PR (#312) could be rebased and merged now.

**Comment by in3otd** [comment]
@ra3xdh , I have merged your PR - didn't see the problem here but your addition does not hurt :grin:

All should be ready to be merged now.

**Comment by ra3xdh** [comment]
@in3otd , @guitorri , Please consider merging of this PR

**Comment by guitorri** [comment]
Looks good to me. Merging now.

**Pull request merged**
