### PR TITLE
A "What's new" window (WIP)

### PR DESCRIPTION
**Pull request by in3otd**
here is a customary "What's new" window that might be useful to inform the (new) users about the most important changes.
As usual, the window is automatically shown at startup (if the current Qucs version is newer than the last version used) and the user can choose not to see the "What's new" window again. It remains available in the 'Help' menu anyway.
I label this as a Work In Progress since
- the actual text to show still needs to be written (not an easy task...)
- I think that the window appearance and design could be improved

qucs_whatsnew

and, as usual, while writing this I (had to) change other stuff; I added a `SemVer` class to handle the comparison between version strings, since there was nothing already that could tell "is version 0.0.18 earlier than 0.0.19 or not?".
The existing `misc::checkVersion()` handled only one kind of comparison ('greather than') and also did not handle major versions (important if we will ever release `Qucs 1.0.0`, one day :grin:)

### CODE REVIEW

**Comment by felix-salfelder** [comment]
what does `Sem` in `SemVer` mean? something like `VersionTriplet` sounds more straightforward (ymmv).

**Comment by in3otd** [comment]
...it was a reference to [Semantic Versioning] (http://semver.org/); even if not supporting all the possibilities of the "official" semantic versioning, it seemed more or less appropriate. But I'm of course open to more descriptive names :grin:

(BTW, this reminds me I think I saw other places in the code where Qucs versions are/should be checked, I'll try to take a look at that...later)

**Comment by felix-salfelder** [comment]
okay, i didn't know about "semantic versioning". from the article

    Software using Semantic Versioning MUST declare a public API. This API could be declared in the code itself or exist strictly in documentation. However it is done, it should be precise and comprehensive.

does QUCS declare a (nonempty) public API? imo it's too early to address versioning issues. we should add your version triplet comparison implementation regardless of the semantics. it makes perfect sense for the "do not show again" checkbox.

there is a `NEWS` file in the QUCS top source directory. it seems to coincide with what the new dialog should display. we should install `NEWS` instead of the independent `whatsnew.html` (or at least generate the latter from `NEWS`).

**Comment by guitorri** [comment]
Originally each sub-directory (`qucs`, `qucs-core`, `qucs-doc`) had a NEWS file. I created a another `qucs/NEWS.md` file. The release script flattens the directories to create the tarball (`qucs` becomes the top dir). I though it made sense to have a single NEWS reflecting all the changes to the project.

I was working on the new NEWS. I am short of time right now... but the latest version is in here:
https://gist.github.com/guitorri/5ce296f510980ec64a45
See the _sample one, which is the result of the cross-referencing script.
Using the Milestones and Tags help a lot on sorting out the contributions.

I am not sure if we should continue with the top NEWS... but I agree that it would make it out look nice on the 'Whats new' dialog.

**Comment by in3otd** [comment]
yep, not sure the "must declare a public API" makes sense for (every) application. But `VersionTriplet` sounds  good enough and does not suggest compliance with Semantic Versioning...

Generating the "What's new" from a `NEWS` file makes sense of course, I thought to use directly that file at the beginning, but then wanted to be able to use some nice formatting with html and did not want to link an external library just to parse one markdown file. Can maybe just translate the markdown to html when compiling/preparing for a release.  
Note that I put the `whatsnew.html` in `qucs/qucs-help/docs/en/` thinking that it could be translated in other languages. Not sure how often that will happen (but looking at the more or less regular contributors we should be able to have at least 4 other languages, besides English), can likely be elsewhere if we do not plan to have it translated.

**Comment by in3otd** [comment]
...changed the name of the version string stuff class as suggested and updated the "What's new" message with the text from guitorri, converted to html with one of the many online converters.

**Comment by guitorri** [comment]
This will be affected by the removal of qucs-help.

**Comment by in3otd** [comment]
> This will be affected by the removal of qucs-help

due to the conflicts you mean? I quickly went thru the code (did not remember what I wrote) and did not see a direct connection with `qucs-help`. I can rebase and clean up for merging, if you think that makes sense.
But as I wrote above, it would be better to have the NEWS file markdown translated automatically to `html` when compiling/preparing for a release, so the *What's new* window text is always up to date.

**Comment by guitorri** [comment]
You have the `whatsnew.html` inside `qucs-help/`.
I thing we should merge #652 before you rebase.

**Pull request closed without merging**
