### PR TITLE
Graph rework

### PR DESCRIPTION
**Pull request by felix-salfelder**
continuing #314.... rebased

@in3otd i did not manage to disable qDebug per-file. i cleaned up some unnecessary output, does this improve the situation on your end?

### CODE REVIEW

**Comment by felix-salfelder** [comment]
rebased ... (minor conflict)

**Comment by in3otd** [comment]
uh, oh, I get a `qucs: graph.cpp:464: void Graph::ScrPt::setIndep(double): Assertion `ScrX>=0 failed.` with some graph here... did we already saw this in the past (cannot remember for sure) ??
Can try to put together a small failing example if you need (current one is quite big)

**Comment by felix-salfelder** [comment]
@in3otd i hope this is about a 3d plot. otherwise, an examples will likely be helpful.

the assertion is probably too harsh, in some intermediate stages it might be legal to insert negative coordinates. this makes sure that the code cannot be debugged easily. still a lot of guesswork involved here `:(`.

**Comment by in3otd** [comment]
no, it's a plain 2D plot.
With your latest commit, I get another assertion fail, `qucs: graph.cpp:471: void Graph::ScrPt::setDep(cplx_t): Assertion ScrX>=0 failed` 

Here is a Qucs package with a small example (remove the `.docx` extension, GitHub needed that...)
Unpack, open the Data Display and follow the instructions there.

[z_tmp_plot.qucs.docx](https://github.com/Qucs/qucs/files/4613/z_tmp_plot.qucs.docx)

**Comment by felix-salfelder** [comment]
thank you.

just to be sure: what does "Unpack" mean?

    $ file z_tmp_plot.qucs 
    z_tmp_plot.qucs: data

my qucs open dielog does not list .qucs in the extensions dropdown.

**Comment by in3otd** [comment]
...sloppy description, I meant "Extract Package", from the GUI, Project->Extract Package (and no, I'm not sure to have seen this feature described in the docs...)

**Comment by felix-salfelder** [comment]
outch. functionally this appears to be a plain file archive. the extract thing created a directory and some files in `$HOME/.qucs`. shouldn't we switch to a more common format?! okay that was off topic.

@in3otd yes, i could reproduce the problem. see the latest commit for a workaround. let me think about how to fix this properly.

**Comment by guitorri** [comment]
Thank you. I was about to ask you to rebase (or merge forward). 
I read the changes. Seems fine, but I did not run yet.

**Comment by felix-salfelder** [comment]
i merged, because the rebase turned out to be messy. will rebase/squash when reviewed.

**Comment by guitorri** [comment]
I know, I tried to rebase myself... went ok till the 7/15 conflicts.

**Comment by guitorri** [comment]
Something is not right. 

develop:
develop
graph_rework:
graph_rework

Another example.
develop:
develop2
graph_rework:
graph_rework2


I just loaded an exiting schematic. The Markers are gone and some Diagrams are painted elsewhere. I mean, if i scroll I see some outlines of diagrams moving around as if the Diagrams are being moved relative to the mouse cursor position.
It is algo giving a the following on the console `Warning: QPainter::end: Painter ended with 5 saved states`
Diagram axes are missing and sometimes the traces are plotted outside.

**Comment by felix-salfelder** [comment]
must be a side effect of the rebase. will have a look. thanks for the test.

`:|`

**Comment by andresmmera** [comment]
I've just tested your last commit for the N={2,4,6,8} cases and I confirm it works :smiley:

**Comment by andresmmera** [comment]
Hello,

I'm taking a look at this and I think that we should go back to ba8c29b57343df5b2f787a5f879cce931ac5b00f and repeat the rebase against develop. I've already done that (several times...) but the branches have diverged a lot, so it is rather difficult to merge them properly...

Now I clearly see that the phasor and waveac diagrams need to be removed. Despite the fact that I honestly appreciate the effort of @gildias, these additions entangle (even more) the qucs code :-S

**Comment by andresmmera** [comment]
My intention is to create a branch removing #682 and then try to rebase this PR against that branch... WIP...

**Comment by felix-salfelder** [comment]
thanks a lot Andres.

**Comment by andresmmera** [comment]
Hello,

I created a [branch (GRAPH_REWORK_wo_682)](https://github.com/andresmmera/qucs/tree/GRAPH_REWORK_wo_PR682) from ba8c29b57343df5b2f787a5f879cce931ac5b00f which contains the latest commits from @felix-salfelder before merging "graph_rework" into develop. Then, as I said above, I created a [branch (Remove682) identical to develop](https://github.com/andresmmera/qucs/tree/Remove682), but removing (manually) the features from #682

Then I rebased "GRAPH_REWORK_wo_682" against "Remove682", made some fixes to make it compile and tested the final result. It works and I didn't find bugs related to the merging process. However, I found a bug coming from ba8c29b57343df5b2f787a5f879cce931ac5b00f (or even before). Please take a look at [this](https://drive.google.com/open?id=1WJ5XZB5geX-JvyYiXEKJ5sIQTHlfYkXc), I guess this is related to the macro in marker.cpp, but I need to take a closer look.

At the light of these results, I think we should follow these steps:

1.  Test "Remove682", open the corresponding PR and merge it into develop
2.  In "GRAPH_REWORK_wo_682", fix the segfault I pointed out before, do more testing, open a PR and merge that into develop

And I think that's all :smile: 
@felix-salfelder @in3otd @ra3xdh @guitorri Do you agree?

370diagram

**Comment by felix-salfelder** [comment]
wow. this looks promising.

about `Remove682`... maybe it makes sense to keep the code in some form, so it will be easier to add back later. e.g. move all the code to some `diagrams/*.cpp`, with some comments, and just remove these from the makefiles.

ba8c29b: will have a look!

**Comment by andresmmera** [comment]
> e.g. move all the code to some diagrams/*.cpp, with some comments, and just remove these from the makefiles.

I agree to keep waveac.h/cpp and phasordiagram.h/cpp and remove them from the building system.
However, IMHO the other code related to #682 (I mean, those pieces of code that affect other files: diagram.cpp, etc.) could be removed since we'll need to figure out an alternative (non-intrusive) way to implement those diagrams.

**Comment by guitorri** [comment]
@andresmmera the first PR is merged.

What about https://github.com/andresmmera/qucs/tree/GRAPH_REWORK_wo_PR682
Does it need rebase or just a PR?

Please prepare the PR and we hunt the crash/bug later on.

**Comment by andresmmera** [comment]
It needs a rebase. I'm working on that, but it might take me a few days to have it done.

**Comment by guitorri** [comment]
Moving to next milestone.

**Pull request closed without merging**
