### PR TITLE
Netlist fix

### PR DESCRIPTION
**Pull request by felix-salfelder**
cleanup. might have side effects, let's see

### CODE REVIEW

**Comment by in3otd** [comment]
uh? The Travis build with `clang` complains *ERROR: files left in build directory after distclean:
./qucs/qucs/qucs_.cpp* but not the other builds ?? This seems about another PR we already merged...
I've restarted the build but it still stops with the same error.

**Comment by felix-salfelder** [comment]
.. not one of the side effects i had expected `:|`

**Comment by guitorri** [comment]
Maybe because your first PR was against `master`?

**Comment by felix-salfelder** [comment]
strange. let's see

**Comment by guitorri** [comment]
Included in #749.

**Pull request closed without merging**
