### PR TITLE
install examples to examplesdir=${pkgdatadir}/examples

### PR DESCRIPTION
**Pull request by felix-salfelder**
maybe #538 needs yet another fix.

### CODE REVIEW

**Comment by in3otd** [comment]
also the [hardcoded path](https://github.com/Qucs/qucs/blob/master/qucs/qucs/main.cpp#L681) (...) in `main.cpp` should be changed accordingly

**Comment by in3otd** [comment]
I have just noticed that the recently added example `filter_optimization.sch` is not listed in the `Makefile.am`, I forgot to add it there also...

Should also the compressed examples be copied, so at least the user sees they are there? There is a subdirectory also, `external_interface/` which is currently not copied.

**Comment by felix-salfelder** [comment]
> not listed in the Makefile.am

generally wildcarding is a bad idea (and discouraged). this is a place where it might not hurt much.
i think it can/should be implemented using `install-local` and `dist-local` targets (or something like that).

    install-local:
        $(INSTALL) -d $(DESTDIR)/$(pkgexamplesdir)
        $(INSTALL) *.sch $(DESTDIR)/$(pkgexamplesdir)

(did not try or check.)

> he compressed examples be copied, 

the compressed examples are really bad. there should be no binary files in the repo or in a tarball.

now we could uncompress them, which will inflate a working copy. to avoid that, we could move the (big?) examples to a seperate `qucs-gui-examples` repository.

if we cannot reproduce copyright/license information of the example files (does anyone care to waste time?), a seperate repo will come in handy...

**Comment by guitorri** [comment]
I will move the compressed examples back to the website: http://qucs.sourceforge.net/examples.html

Most of them are already there.
At some point I think we should make a selection of representative things from the `qucs-test` repository and use as examples. `qucs-test` already contains majority of the examples.

Indeed, license information is a big question. In most cases there is no track record of authorship.

**Comment by guitorri** [comment]
Ok. I moved the compressed examples to the website. The last 4 in *Complete projects* where missing in the website. I will later send another PR to remove all compressed examples, and move the examples directory inside `qucs/`.

**Pull request merged**
