### PR TITLE
Spanish translation updated

### PR DESCRIPTION
**Pull request by andresmmera**
Hello, 

This PR is simply an update and correction of the Spanish translation. I've found that many entries were not translated and a number of errors.

### CODE REVIEW

**Comment by guitorri** [comment]
Hum. Can you try to rebase your changes to release-0.0.19? 
In the future please consider giving [Qucs Transifex](https://www.transifex.com/qucs/qucs-desktop/) a try. Onde day I hope to have it synched with our repo, so code changes propagate directly to the translators.

**Comment by andresmmera** [comment]
I've just done it :+1: 
Next time, I'll use Transifex

**Comment by guitorri** [comment]
Ok, it is based on release-0.0.19 but you want to merge on master? 
I can reopen your PR or merge it locally. Just want to make sure it is based on release-0.0.19.

**Comment by andresmmera** [comment]
Hang on... After making a diff of qucs_es.ts between this PR and release-0.0.19 I've realized that, for some reason, I've directly committed the translation to release-0.0.19 on Jun 10, 2016

See https://github.com/Qucs/qucs/commit/33c9e04a2b198120737a0d947b66fd1af84751bb

...This PR must be closed.
I don't really know why I committed without a PR. I'm sorry, Guilherme :(

**Comment by guitorri** [comment]
No problem. Thank you for tracking it down.

**Pull request closed without merging**
