### PR TITLE
Allow pasting from future versions

### PR DESCRIPTION
**Pull request by in3otd**
Fix for #593, as described there, copied here for convenience:

- if *load from future versions* is enabled:
  - show future-version schematic in the tree view
  - open them without any warning message
  - paste from future versions without any warning message
- if *load from future versions* is **not** enabled:
  - do **not** show future-version schematic in the tree view
  - abort opening them (if forced thru the *Open* dialog) with an error message
  - abort pasting from future versions with an error message

### CODE REVIEW

**Comment by guitorri** [comment]
I rebased to fix a conflict, added a commit and pushed `-f` back to your branch.  
I hope it is ok, otherwise we keep bouncing messages and PRs around... What do you think?

**Comment by in3otd** [comment]
> I hope it is ok

if you mean the `push -f` on "my" PR, that's fine with me.

Thanks for the added commit to refresh the project in case the setting is changed.

A small detail: I've just notices that [here](https://github.com/Qucs/qucs/pull/607/commits/19ea4772a29f97a18ad9a53c891d5382f6e5e7e0#diff-21d4c99ec9cdd653d28a62942ff16889R135) I should probably have done as [here](https://github.com/Qucs/qucs/pull/607/commits/19ea4772a29f97a18ad9a53c891d5382f6e5e7e0#diff-21d4c99ec9cdd653d28a62942ff16889R875). Does not make a difference in practice, I think.

**Comment by guitorri** [comment]
It will create 2 strings to be translated, but the behavior is probably the same.

**Comment by guitorri** [comment]
I will fix that.

**Pull request merged**
