### PR TITLE
fix projectView shows dot filename wrong place

### PR DESCRIPTION
**Pull request by yodalee**
The repeat steps:
1. Create a filename with dot like: MyFile_v0.1.sch
2. The file will shows in category "Others" in project content
   But it should be in "Schematics"

The cause:
It's caused by projectView.cpp, when it categorize files by extension
it get extension name with following line:
extName = QFileInfo(workPath.filePath(fileName)).completeSuffix();
which get the complete suffix:
complete suffic of `MyFile_v.0.1.sch` will be `0.1.sch`
which is not a '*.sch" file.

The fix:
Change completeSuffix into suffix
extName = QFileInfo(workPath.filePath(fileName)).suffix();
so filename with dot still get right extensions

### CODE REVIEW

**Comment by yodalee** [comment]
review = @in3otd 
solved issue = #231

**Comment by in3otd** [comment]
file *renaming* works well now, but when I *open* a file with a dot in its name, like `MyFile_v.0.1.sch` by double clicking on it in the Project Content, it is opened as a *text document*. Can you take a look at this @yodalee ?

**Comment by yodalee** [comment]
It's also cause be `completeSuffix()`, I add a commit to fix it.
This branch may need squash before merge.

**Comment by in3otd** [comment]
ok, but since `completeSuffix()` has been (correctly) changed to `suffix()` also the complementary `baseName()` calls needed to be changed to `completeBaseName()` in `slotCMenuCopy()` and `slotCMenuRename()`, otherwise these operations will lost part of the file name, if it contains dots...

**Comment by yodalee** [comment]
make sense =w=, fixed.

**Pull request merged**
