### PR TITLE
Fix windows build

### PR DESCRIPTION
**Pull request by guitorri**
Closes issue #171

### CODE REVIEW

**Comment by guitorri** [comment]
TODO:
- [ ] should be `static const`
- [ ] rename M_PI to pi, avoid collision... looks nicer

**Comment by guitorri** [comment]
@in3otd would you like to comment the above changes?

**Comment by guitorri** [comment]
Merged in 6c1fb1e964c3a9199e7ba433fc27aa8fabb16025

**Comment by in3otd** [comment]
...you are going too fast :smile:
sorry no time to closely look at this, only just tried to build on windows also here and it works as expected.
Had a couple of questions on the steps in the wiki, will discuss later.

**Comment by guitorri** [comment]
Hehe, I gave a little push to fix the Windows build. Soon I will add an AppVeyor instance (Travis CI for Windows) to test the build on the Windows platform. Some day it would be interesting to give it a try with the Visual Studio compiler... 
I did some small updates on the wiki... feel free to ask and modify.

**Comment by in3otd** [comment]
regarding the instructions on the Wiki (but it's  the same on Linux), if I clone the git repository and follow the instructions to build `Qucs Core` when I do `sh bootstrap.sh` I get `Could not locate adms autogen script in ./adms, you may use configure with --disable-adms to use installed version` which seems a bit of a chicken and egg problem since `configure` is not available because `bootstrap.sh` did not run... If I clone the submodules then of course it works, but should be not needed, as we use the pre-built binary for adms...

**Comment by guitorri** [comment]
@in3otd the ADMS bootstrap should be fixed in 13ae936ee3e87b20dbd5611e902dc8ed2a6ef440

**Pull request closed without merging**
