### PR TITLE
Tutorial on RF Amplifiers with S-Parameter Techniques

### PR DESCRIPTION
**Pull request by gogobers**
Added a Tutorial to design RF-Amplifiers using S-Parameter techniques, such as
gain- and noisecircles. Complete project is available, but git ignores part of
the files (such as .sch etc.)

### CODE REVIEW

**Comment by in3otd** [comment]
@gogobers , a couple of `Makefile`s needed to be updated to have your tutorial properly included with the other Qucs docs; I'll push the needed changes later.
Out of curiosity, why did you use `w2dbm()` to obtain the noise factor in dB and not just `dB()` as done for the S-parameters? Of course the numerical results is the same, but since also the noise factor is a pure number it makes sense to use the `dB()` function for that also.
The schematics are ignored since they are listed in `.gitignore`, you can add an exception for the directory containing the schematics. Or put them in the examples, maybe.

@guitorri , the build on Travis fails while trying to expand the `adms` downloaded from dropbox https://travis-ci.org/Qucs/qucs/jobs/179692855#L753 . Is version `2.3.4` still available there?
Besides, should we include this in `0.0.19` already? In case, some adaptation may be needed since the `qucs-doc` build system has been changed a bit recently.

**Comment by guitorri** [comment]
Yes, sorry. Please hold on a bit.
I am about to merge `release-0.0.19` into `master` and `develop`. Things should be back to normal. 

I forgot `develop` was pulling `adms-2.3.4` from my Dropbox (added during a period SourceForge was on constant shortage) and moved things around.

You can cherry-pick 55a16ac583 and b9b414efd if you really want.

However, the merge will land a bunch of changes on `qucs-doc` makefiles, I suggest you wait just a bit.

**Comment by gogobers** [comment]
Hallo,
@in3otd: I added the dpl and sch files now (needed to change gitignore 
for that, as mentioned).
I took w2dBm for no particular reason, I probably just stepped on that 
function and wanted to try it..
Best regards
Gerald


Am 29.11.2016 um 21:22 schrieb in3otd:

**Comment by guitorri** [comment]
I will merge #622 so you guys can use the latest changes on the build system.

**Comment by in3otd** [comment]
rebased to the current `develop` branch and updated to use the latest doc build system.
Builds fine here locally.

**Comment by in3otd** [comment]
? Travis on OS X fails: `qucs-test` fails on `DC_SW_fgummel_prj` , see https://travis-ci.org/Qucs/qucs/jobs/191903593#L4297-L4299 . Likely a "random" failure, as reported in #623 ...

**Comment by guitorri** [comment]
Please ignore OSX, it is not building `qucs-doc` anyway. Feel free to merge.

I see OSX failing on:
- `DC_AC_bbv_prj`: https://travis-ci.org/Qucs/qucs/jobs/191903593#L4447
- `DC_SW_preregulator_prj`: https://travis-ci.org/Qucs/qucs/jobs/191903593#L4461

Maybe it Travis was rerun and `DC_SW_fgummel_prj` is no longer showing up as error.

I can no longer reproduce these errors as I am running a newer OSX than Travis. I will set `qucs-test` to skip these tests. If "random" issues show up again I guess we should disable`qucs-test` for OSX.

**Comment by in3otd** [comment]
> Maybe it Travis was rerun and `DC_SW_fgummel_prj` is no longer showing up as error.

yes, I restarted Travis for OS X and that failure did not show up anymore, but there was a different failing testcase... . IIUC, `qucs-test` fails with error code -11 which may be "segmentation fault". Hope that this is not due to the (in)famous `multiprocessing` that has some issues on Windows...

**Pull request merged**
