### PR TITLE
Window build fixes

### PR DESCRIPTION
**Pull request by in3otd**
let's try the fix for gperf-3.04 and a guess for the Qt link error...

### CODE REVIEW

**Comment by in3otd** [comment]
...oops, forgot to bring in guitorri's fix...

**Comment by guitorri** [comment]
AppVeyor/MSYS2 is broken ATM. I am trying to  figure out how to fix it.

**Comment by in3otd** [comment]
yes, I too I'm trying to figure out why and wanted to test something :grin:

**Comment by guitorri** [comment]
My guess is that it its mixing up things from the `cmd` environment from Windows with the `bash` environment from MSYS2. :confused:

**Comment by in3otd** [comment]
I thought the error was not directly related to that, but I wondered why you used `bash` to do (almost) everything, couldn't it be done just using the windows shell?

**Comment by guitorri** [comment]
In theory, when you fire up the MSYS2 `bash`, all the PATHs should be properly set to use thinks installed inside the `C:\msys64\`. It becomes an isolated environment with usual Linux tools. I challenge you to run autotools on the Windows `cmd`...

**Comment by in3otd** [comment]
er, my understanding was a little different, that the MSYS2 `bash` "just" provides a nice shell which can talk with both the Windows and Linux-like worlds (and make the two talk together) but does not provide an isolated environment, quite the contrary, as it allows you to use application from both worlds (e.g. you can start Notepad from MSYS2 bash...)

I am just compiling `qucs` in a `cmd` shell, run `./bootstrap`, `./configure`, now just finished to compile the qucs GUI, seems to work...

**Comment by in3otd** [comment]
...AppVeyor works again now :tada:

Travis also passed, but on OS X there are several lines like
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-exec-hook
Creating MacOSX applications...
Copying and setting up MacOSX/Qt framework...
running: macdeployqt /Users/travis/build/Qucs/qucs/qucs-0.0.19/_inst/bin/qucs.app
ERROR: no file at "/usr/local/pgsql/lib/libpq.5.dylib" 
running: macdeployqt /Users/travis/build/Qucs/qucs/qucs-0.0.19/_inst/bin/qucsattenuator.app
ERROR: no file at "/usr/local/pgsql/lib/libpq.5.dylib" 
running: macdeployqt /Users/travis/build/Qucs/qucs/qucs-0.0.19/_inst/bin/qucsfilter.app
ERROR: no file at "/usr/local/pgsql/lib/libpq.5.dylib" 
running: macdeployqt /Users/travis/build/Qucs/qucs/qucs-0.0.19/_inst/bin/qucsactivefilter.app
ERROR: no file at "/usr/local/pgsql/lib/libpq.5.dylib" 
running: macdeployqt /Users/travis/build/Qucs/qucs/qucs-0.0.19/_inst/bin/qucshelp.app
ERROR: no file at "/usr/local/pgsql/lib/libpq.5.dylib" 
running: macdeployqt /Users/travis/build/Qucs/qucs/qucs-0.0.19/_inst/bin/qucslib.app
ERROR: no file at "/usr/local/pgsql/lib/libpq.5.dylib" 
running: macdeployqt /Users/travis/build/Qucs/qucs/qucs-0.0.19/_inst/bin/qucsedit.app
ERROR: no file at "/usr/local/pgsql/lib/libpq.5.dylib" 
running: macdeployqt /Users/travis/build/Qucs/qucs/qucs-0.0.19/_inst/bin/qucsrescodes.app
ERROR: no file at "/usr/local/pgsql/lib/libpq.5.dylib" 
running: macdeployqt /Users/travis/build/Qucs/qucs/qucs-0.0.19/_inst/bin/qucstrans.app
ERROR: no file at "/usr/local/pgsql/lib/libpq.5.dylib" 
make[4]: Nothing to be done for `install-data-am'.
```

don't know if these are relevant...

**Comment by guitorri** [comment]
It works! :smile:

You are right, `bash` it is just a nice shell. I use it as a isolated environment (not prepenidng the windows PATH with msys path). Perhaps we can clean up the appveyor script further. Or collapse it all into a single bash (or cmd) script that any user could use.

**Comment by guitorri** [comment]
those macdeployqt errors are not relevant. for some reason it is tryng to bundle libraries that are not needed by Qt

**Pull request merged**
