### PR TITLE
Use left recursion for parsing S-parameters files

### LINKED ISSUE #789: S-parameters parser fails on big files
S-parameters file parser fails on (relatively) big files, see e.g. https://sourceforge.net/p/qucs/discussion/311049/thread/4aeb8b6e/ . I can reproduce this on a 100 MB file, with about 600000 lines.
Increasing YYMAXDEPTH as suggested can solve the issue but looking at the Bison docs it seems that [defining rules differently](https://www.gnu.org/software/bison/manual/html_node/Recursion.html) may help.

### PR DESCRIPTION
**Pull request by in3otd**
Fix #789.
Seems to work fine on all the S parameters file I have at hand here (from 2 to 40 ports and size up to 100+ MB).

### CODE REVIEW

**Comment by Kathy626** [comment]
what is the maximum file size you can upload after this been fixed?

**Comment by Kathy626** [comment]
After I modified code, and make all , somehow I got error 
` make all
/bin/sh ../build-aux/ylwrap parse_touchstone.ypp y.tab.c parse_touchstone.cpp y.tab.h `echo parse_touchstone.cpp | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/` y.output parse_touchstone.output -- bison -y -d -t 
/home/usr/Documents/qucs-0.0.19/qucs-core/src/parse_touchstone.ypp:110.15-22: error: symbol Dataline is used, but is not defined as a token and has no rules
/home/usr/Documents/qucs-0.0.19/qucs-core/src/parse_touchstone.ypp:112.27-28: error: $2 of ‘Dataset’ has no declared type
/home/usr/Documents/qucs-0.0.19/qucs-core/src/parse_touchstone.ypp:114.32-33: error: $2 of ‘Dataset’ has no declared type
/home/usr/Documents/qucs-0.0.19/qucs-core/src/parse_touchstone.ypp:115.23-24: error: $2 of ‘Dataset’ has no declared type
make: *** [parse_touchstone.cpp] Error 1`
This is really weird

**Comment by in3otd** [comment]
yep, that's really strange, the build here is fine and also [Travis](https://travis-ci.org/Qucs/qucs/builds/360563438) and [AppVeyor](https://ci.appveyor.com/project/qucs/qucs/build/1.0.1601) show no issues.
Did you pull the branch were the changes were made? (but there's just one changed file).
BTW, for Windows you can get ready-made binaries for this PR [here](https://ci.appveyor.com/project/qucs/qucs/build/1.0.1601/job/wmllf8bgdn4llbon/artifacts).

**Comment by Kathy626** [comment]
I chatted, I didn't use branch, instead, I have went into the Source Code for modification. But I don't think that matters?!  OR does it master a lot?
As you mentioned there is one changed file, but I saw three changed file, they are check_touchstone.cpp and check_touchstone.h, and parse_touchstone.ypp. So did you only changed .ypp file and the other two is automake?

**Comment by in3otd** [comment]
yep, the changed files are three actually, I corrected my comment above - I was thinking just at the one with the most changes. In any case, if you modified the files manually it should of course work fine.

**Pull request merged**
