### PR TITLE
Fix CMake and various warnings after merging #682

### PR DESCRIPTION
**Pull request by ra3xdh**
This PR solves the following issues after merging #682:

* CMake became broken. Added proper filenames in `diagrams/CMakeLists.txt`
* There was a lot of deprecation warnings in `diagramdialog.cpp` on `QComboBox::inserItem()`. Replased by `QComboBox::addItem()`.
* Fixed "unused variable"  `i` in `diagramdialog.cpp`. This variable was indeed unused.

There remains an unfixed warning in `marker.cpp` Line 388. It contains the following code: 
~~~
if(n == diag()->nfreqt) n == diag()->nfreqt-1;
~~~

I didn't understand what this code should do. It seems, the  comparison `==` should be replaced by assignment `=`. The current line does nothing, but all works as expected. @gildias, Could you please clarify, what exactly did you mean?

### CODE REVIEW

**Comment by ra3xdh** [comment]
>  marker.cpp Line 388. 
I understood now what it should do. It checks the index limits. There should be an assignment.

**Comment by gildas** [comment]
@ra3xdh, I think you got the wrong person.

**Comment by ra3xdh** [comment]
@gildas,  Sorry, I meant  @gildias , an author of #682.

**Comment by gildas** [comment]
Hey no problem.

**Comment by andresmmera** [comment]
My fault. I didn't catch these issues.
I'll take a look to this PR as soon as I can.

**Comment by andresmmera** [comment]
@gildias and me detected some more warnings:

>diagramdialog.cpp: In member function ‘void DiagramDialog::addvar(QString)’:
diagramdialog.cpp:1642:62: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
     if( l != -1 && Var2.size() == (l + a.size()) && !m.size()>0)//Var2.size == (l + a.size()) in case of voltage (.v) to don't let pass a variable li
                                                              ^
diagramdialog.cpp:1645:21: warning: ‘I’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       slotTakeVar(I);
                     ^
graph.cpp: In member function ‘int Graph::getSelectedP(int, int)’:
graph.cpp:308:81: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
       if(((f1 >= f3) && (xn >= f3)  && (xn <= f1)) || (f3 >= f1) && (xn >= f1)  && (xn <= f3))

Working on that

**Comment by andresmmera** [comment]
See https://github.com/ra3xdh/qucs/pull/28

**Comment by andresmmera** [comment]
See https://github.com/ra3xdh/qucs/pull/29 too

**Comment by ra3xdh** [comment]
@andresmmera , I have just merged your PRs. Yes, warnings in `qucs-filter` could be merged too.

**Comment by andresmmera** [comment]
I reviewed and tested this PR and I found no more issues so I believe it is ready to merge

**Pull request merged**
