### PR TITLE
Rebase of #356

### PR DESCRIPTION
**Pull request by ra3xdh**
This PR contains Circular waveguide component rebased (#356). I squashed all commits in one, because some commits contain accidentally committed auto-generated files. In other case, these files will be forever presented in index. @andresmmera , Please look at this.

### CODE REVIEW

**Comment by andresmmera** [comment]
@ra3xdh I've just reviewed the PR locally and everything seems to be correct. 
Please excuse my ignorance, but am I supposed to merge this PR?

(BTW, I'll take a look if I left auto-generated stuff in the other PRs)

**Comment by in3otd** [comment]
@andresmmera , it would be nice to have a test schematic for this new component to include in `qucs-test` (will of course be a separate PR). I saw you included [this schematic](https://dl.dropboxusercontent.com/u/21294824/CircularWaveguide.sch) in your original PR, it's still good for generating some reference results?

**Comment by andresmmera** [comment]
From my point of view, this example shows the narrowband (and periodic) behaviour of a circular waveguide, so I reckon that it could be used as reference. Anyway, I'll check some books/papers in order to find a more meaninful example.

**Comment by ra3xdh** [comment]
@andresmmera , I think, this is am exception, where self-merging is possible, because this PRs doesn't contain my own commits. 

@in3otd , I have added a tests development into the tasklist in #651.

**Pull request merged**
